---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: 1.0.31
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      size: "256Mi"
      storageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: portainer.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: portainer-tls
          hosts:
            - portainer.${SECRET_DOMAIN}
