---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: openldap-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    global:
      storageClass: longhorn
      ldapDomain: "${SECRET_DOMAIN}"
      adminPassword: "${SECRET_DEFAULT_PASSWORD}"
      configPassword: "${SECRET_DEFAULT_PASSWORD}"
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${LB_LDAP_ADDR}"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 512Mi
    env:
      LDAP_ORGANISATION: "${SECRET_DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
    customTLS:
      enabled: false
    ltb-passwd:
      enabled: false
    phpldapadmin:
      enabled: true
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        memory: "128Mi"
    customLdifFiles:
      00-organizational-units.ldif: |-
        dn: ou=Groups,{{ LDAP_BASE_DN }}
        objectClass: organizationalUnit
        ou: Groups

        dn: ou=People,{{ LDAP_BASE_DN }}
        objectClass: organizationalUnit
        ou: People

        dn: ou=Services,{{ LDAP_BASE_DN }}
        objectClass: organizationalUnit
        ou: Services

      01-default-users.ldif: |-
        dn: uid=${SECRET_DEFAULT_USERNAME},ou=People,{{ LDAP_BASE_DN }}
        objectClass: inetOrgPerson
        objectClass: organizationalPerson
        objectClass: person
        objectClass: top
        uid: ${SECRET_DEFAULT_USERNAME}
        cn: ${SECRET_DEFAULT_USERNAME}
        sn: ${SECRET_DEFAULT_USERNAME}
        mail: ${SECRET_DEFAULT_EMAIL}
        userPassword: ${SECRET_DEFAULT_PASSWORD}

      02-default-service-accounts.ldif: |-
        dn: uid=authelia,ou=Services,{{ LDAP_BASE_DN }}
        objectClass: account
        objectClass: simpleSecurityObject
        objectClass: top
        uid: authelia
        userPassword: ${SECRET_DEFAULT_PASSWORD}

        dn: uid=keycloak,ou=Services,{{ LDAP_BASE_DN }}
        objectClass: account
        objectClass: simpleSecurityObject
        objectClass: top
        uid: keycloak
        userPassword: ${SECRET_DEFAULT_PASSWORD}

        dn: uid=manictime,ou=Services,{{ LDAP_BASE_DN }}
        objectClass: account
        objectClass: simpleSecurityObject
        objectClass: top
        uid: manictime
        userPassword: ${SECRET_DEFAULT_PASSWORD}

      03-default-groups.ldif: |-
        dn: cn=Admins,ou=Groups,{{ LDAP_BASE_DN }}
        objectClass: groupOfUniqueNames
        objectClass: top
        cn: Admins
        uniqueMember: uid=${SECRET_DEFAULT_USERNAME},ou=People,{{ LDAP_BASE_DN }}

        dn: cn=Users,ou=Groups,{{ LDAP_BASE_DN }}
        objectClass: groupOfUniqueNames
        objectClass: top
        cn: Users
        uniqueMember:
