apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:IVuTLsY/FyDUqhFxcW7xoQFI,iv:KAA1zJjCisExE0rO7Qv7gU/FjLB1BC7AH7H1IzzI2Po=,tag:Y97iCD/0D98RS6t0iTsMXg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:b+GYUxgr/9oMTQ4C4ukNvmTgoIVdH10jgc54UteMiZfHibgOkA==,iv:nLz6pn3vZa06KHAiz1wvcaVs0Ed3m08mPcqbajQ6k9s=,tag:ORphDqE67owvYs15jq9H7A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Tx5PrpPC0YBCjswvbNM8,iv:krS8u4csnKalBNai2F+IXxBovRgZDkasTvgY8F4dLto=,tag:opQudBKRlhVmFyOxodupUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eXl1c1ZaUytNK2ozd2M5
            azRZL091b1M5NjMrRmNZU2tpdWRCN1h6WkFzCkN1dHU4bUdudGQ3M0IwcVVYSTVK
            TUp3S1N0VzNWVGFOUWtPQnhUOU9QTWMKLS0tIE9nSi9iMVY0Z2UvU2YrcmhheFZh
            dnJhRkx2RTFIMWtpd2crcE9ma2ZoeG8K0kDxbn+q2LlcyK8WyGsUhW54AT+CdqV1
            n7a+5fPRQg3c6krc01EHM0fBgKwcLiYVMKLuksAw4mc+l1uNWhdjJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T22:59:14Z"
    mac: ENC[AES256_GCM,data:hs7tVDPKXGHNLXjI0OhzqIbFl7qeeBsOFgAL+O6xUBoUoDjV8ivgJXAFJuaqPbMHtB3fMHof4aTZm7FKpMPXK/5HMSs0AiLL5IVW9PJgMRp6X+tsE7ro2vo2L6D2ZzwOnC8ZWrXWkMHMXJqGADtX4CGKqSE0cQ4R0Zl52l+ADfc=,iv:dCIerI1SLdSloYRubE6ezit244OoDHJc4ht5M4Dk7zI=,tag:2lvpN7r5yo53b5AMlC0+kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
