apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:0Yv4SNMYw5d3H6ruNEAoUctJ,iv:uOmnJggcCreUW2nTkgEQmC84gl1z2WLvpZD+R4Sb/cY=,tag:t7k2k4QrGOnHCT9l0SjMcg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Y3FXm/+eRKHkv9uQPzOexa3R3TxXgzC2B+wCXsRnviEVN5A6Nw==,iv:4OTFGWUR4KVhkjOvuQE2rYXWt6j/rXfgUfPqxiz9KgU=,tag:iA5y5wP067tl9J6yTPSeAw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:H3nIYXi1qmqepXXVhW2f,iv:uG7fxUSeRpyNvrrGl0N5z+d4qdKYhhMQn5jkwTk1GHM=,tag:pyXRlnLbLJLJzs0Uil6puQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOejBqTnBNZXFGSjl1ZU45
            RS9XcExmUmY2TGFCWkhYUXZnM25wS2JjakZVCmdrWTQzQ3VzVEZiR0M0RW02VVU0
            cVBOMFhWUkR5a0dpMktHaGMvQXdrZm8KLS0tIEcwckpDdlFaaDk2a0l3aHNQdzdp
            NDRVRHk5K1JYTW11WWtJZFVzK1I2eG8KRMaGUGn23SAna+KvTyjZPSFwdzLrL18I
            341mLAwmZHzRbBKvuj0Z3D23Vvr7Zg0c5wFchR5CvUvgIk/5LvmzmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T04:33:28Z"
    mac: ENC[AES256_GCM,data:tQj0oP5DLCUc3zUi4vp8+i201ynihCr18g5SEMiGv50vdBRlipcSlmQhLMEV+CSsIMey3vrP4HGWoon8c4OZtsodz7VIELKEmVMSSonoOaPyc3hCDDoI/7u+J6N2q5nK8lLmUuVlYfWaKfJWn12q8Q1s9BOWOkOT1WtX0K0lrSg=,iv:Vn1Ni3Ftu/OwLBMRitBzhSgAr0im4y4Lwb3oYkUJAbc=,tag:FbxIEw5N0GLV8z5wkD4rrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
