apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:wUpmOUnIzOi3u1e4AdlOCDj3,iv:iiOtfIEwyPmVxldS55zf378SZWfAzPKbLkzkrEY6LA8=,tag:ysNM2eJtbqv/j5XFCPYR/g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:RteF/COYL1gTpOdbJLGQxXV9VruepvH+LWs/gaMeG8nAFvgaEw==,iv:MTe2TNnPEsvAfMLsetaf7/oWP0vj+XP3IF0TVKmiIwk=,tag:NYiO1gYDAlVErz7YylSD0g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:z66jAXGMfEqpaZZGgpct,iv:9tctMyuahXVwibspWEGwSvRY1Wuzfv+H1vxH7tVe0ow=,tag:xtG6aubpap9bsCXV20tLLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGdlbWFZWi9mZC9jMEp5
            ci9lcjFGT1FiWnNpYVlENnZMTUFBR3JCUnpBCkl1U0xTSGhVQXVDclBDNFZvdDBN
            VEYyOGgwYWJkYmZ1SjRhYWJPNjgrMmMKLS0tIGZHcWtXUTJrU25sem9Ed1JFWkR4
            TWtrcjlXeThSNU91UzNmNDNyMGRydjQKYE6yfojFVx0XC5YrRNK/Q1eDIQq5Q5/y
            GipATzemPO8/lHWg0S85Pyrplgh15ByqHPf4SeH6feY16BKRVKp7dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:39:57Z"
    mac: ENC[AES256_GCM,data:TGy6TH1JlM6fmIWYEtHsq2QwhHBYoDwER+P9qd0wgkT5ORc+xq0vRmOQO8bHCkAeTnPyt8EiGqL1FEQzgcBFy9l8ibD3l/+N4qN/Zoa05iwiWdCY41tuk2AgoJOKVT4OPBG//MkSJu4PGypkfAkR5DWxKRgkbYCUKlSYgR+xCqI=,iv:vCe0TvRXYbTXyLeSHUDFXuY6NDUlNmUolzA7UB1x3Yk=,tag:I5cap8f7tYGFealOyenkIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
