apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:U/oER9GqzsfpPtseTOYwgFqB,iv:bkm7CpeXyq1/xRAX2rKWXzwBHhCIJhf6TWHKYKvoRQU=,tag:beqDgMT2X/DZqT2D+Za7xg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:dAEzkRf2oHk2XEP+anWMURcd+oQ75SBKf3FQ2ZokL3yD4NgQzQ==,iv:C9xd/m1YeCEb2ISc965epg+fqMz9YLZkYGWER1cmR6Y=,tag:Edfs2B1HhEFwSgbd+kgZCA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:yb4gfq4TNbdY0ALSvumk,iv:cQZpiSx1s+3lRdOAgUPCp05L0yqhYE88Kt7x98ONwjk=,tag:DeXUmhvdZHj5F94tdXh0Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUzNKNEZBa3NabnRkZVhG
            NVBxY3BnM0ZiYnZRUUlHM3J3Y1FVS2R6Y0VJCjI5UUl2aGFnZ2RLdUtiRGlzc1dF
            R2lSbXhyZHI2MGdCU05LRnpxSEVsSVEKLS0tIE5hN0JVbEdKTHN4ZThOWHBld2xZ
            UTkzcStKMGhtR0ZLb0g0VmtyaEZMLzQK7VKwvwT750AXQMNp+hVW+c23c0eI69oz
            rZpKjz/BdVbYI/fo9jJrVFFfTfbSKu8J8knx2Wk6lYiHq7IgTJkZig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T07:34:40Z"
    mac: ENC[AES256_GCM,data:7drqNDh1naB4qig6O9Dz8WzYfv6c+MV+as4qmPCY8TnJfML2aMVvRrUYn7P4T9c672BDKScLy4jstYy6JSIgOpoSoy7bG1iG6CPUdkkx8FRkNfHr4geiN6oMahkxYW9rNsfCDkgV2M8UVgvXyFaKaV6FHU3pAsoQncdmt4F8vcM=,iv:SF5mxq2dAF65rYFbRDNNondIhOY1WUTqTy1DOzWAx+0=,tag:L1gJAGSlJrg37eEYAYzhbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
