---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: actions-runner-controller-secret
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: secret/arc--github-app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: secret/arc--github-app-installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: key/arc--github-app-private-key
