---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      version: v4.2.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs-charts
        namespace: flux-system
  upgrade:
    remediation:
      strategy: uninstall
  values:
    kubeletDir: /var/lib/kubelet
    controller:
      replicas: 1
