---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared-media-pv
spec:
  storageClassName: nfs-shared-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SVC_NAS_ADDR}
    path: /volume1/share/media
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-media
  resources:
    requests:
      storage: 1Mi
