---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-shared-videos-pv
spec:
  storageClassName: nfs-media-shared-videos
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SVC_NAS_ADDR}
    path: /volume1/share/videos
  mountOptions:
  - nfsvers=4.1
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-shared-videos-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-media-shared-videos
  resources:
    requests:
      storage: 1Mi
