---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-dns-source
  namespace: flux-system
spec:
  interval: 30m
  # renovate: datasource=github-releases
  url: https://github.com/kubernetes-sigs/external-dns.git
  ref:
    tag: v0.13.1
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/docs/contributing/crd-source/crd-manifest.yaml
