---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-snapshotter-source
  namespace: flux-system
spec:
  interval: 30m
  # renovate: datasource=github-releases
  url: https://github.com/kubernetes-csi/external-snapshotter.git
  ref:
    tag: v5.0.1
