---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manictime-data
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
