---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
