---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: external-secrets
  data:
  - secretKey: UNIFI_SERVICE_ADDR
    remoteRef:
      key: UNIFI-SERVICE-ADDR
  - secretKey: NAS_SERVICE_ADDR
    remoteRef:
      key: NAS-SERVICE-ADDR
  - secretKey: PLEX_SERVICE_ADDR
    remoteRef:
      key: PLEX-SERVICE-ADDR
