---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backups-k10-pv
spec:
  storageClassName: nfs-backups-k10
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SVC_NAS_ADDR}
    path: /volume1/backups/k10
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backups-k10-pvc
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-backups-k10
  resources:
    requests:
      storage: 1Mi
