---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.6.15
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: openldap
      namespace: networking
  values:
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LB_POSTGRES_ADDR}"
      initdb:
        scripts:
          01-init-authelia.sql: |
            CREATE USER authelia;
            CREATE DATABASE authelia WITH OWNER = authelia;

            CREATE USER keycloak;
            CREATE DATABASE keycloak WITH OWNER = keycloak;

            CREATE USER manictime;
            CREATE DATABASE manictimecore WITH OWNER = manictime;
            CREATE DATABASE manictimereports WITH OWNER = manictime;
    auth:
      postgresPassword: "${SECRET_DEFAULT_PASSWORD}"
    ldap:
      enabled: true
      server: openldap.networking.svc.cluster.local
      port: 389
      baseDN: "${LDAP_BASE_DN}"
      bindDN: "cn=admin,${LDAP_BASE_DN}"
      bind_password: "${SECRET_DEFAULT_PASSWORD}"
      search_attr: uid
