kind: ENC[AES256_GCM,data:1JBfsbfS,iv:7htxtOoAksUPZ+yDqsMzvQIYnU0oqX5Ccj2crFqNL84=,tag:LpKkExuXvQq0HUHHehymbQ==,type:str]
ansible_user: ENC[AES256_GCM,data:w+VwWx35WQ==,iv:du3qiQ6piBzWfEYqAy/OGogMqJNu53BDTwRw2/Gh4Bg=,tag:r6GZMTtoDXWholXqI0jQMw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:F9DqbNsEs2/B,iv:eIsTUFrVZi+JWtxEJQswIamKRdwuXR/LMzoIgX7exmo=,tag:9I4m82DdI/JdgSs/GONPww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUHNMTllGMFdOM0tEUlVh
            Y0FNSGtpdktIaGU3M2l6cmlSUWFTeWhFYkRZClNLOXBBNitSWjZMY29SVTA3TGFU
            aCs5bU5mNGpPaFZzNXNYdXh4ZjhWMVUKLS0tIER3YXBqdGlYQjFhOW1TNU13dkg4
            Z0FqRmN1aUJYb0FBZ3BRNUx0MmtISUkKfCUDsCmyeERi9KmoTUmWqh+TSUbjcUhQ
            G2vEholtCoq/fSwY6nA1/5xJ+1XkBTDvzFWVs1qG5xLwzWCzEDIfoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T05:00:32Z"
    mac: ENC[AES256_GCM,data:RnYjOvpJ9x9Je32M88jMKftolSsgbQD3KbVENDxlija1oUaJLKIoIW8+DlK/YPhdGXnjSb15o5eyeCkVxt0KcKBzPdphUwVX0mSz1M2MMXZkICFCzePLSOG5OcpAduxLS0702q4sj/zNyL0YnLily8UTJye6LsdnS2yzeeMvkas=,iv:9yZ1t5Q74edv2bE6D3Fr6UOLdzY0vxW61ZS6ktcKmdU=,tag:5snxe88sYJb+FrdoLnwfrg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
