kind: ENC[AES256_GCM,data:OLt6FHer,iv:ZCVpJ7Mj+5kfLGrAZWwVWezHpjEpxkO1MsA0l0zBTa0=,tag:6McqwHsmx2S5eoyY+tWRKQ==,type:str]
ansible_user: ENC[AES256_GCM,data:cXMsDf7x6w==,iv:XDHJ2kRsasulsREV9+Zxdsls3lDdf5hioQGOnpra/G0=,tag:U41WCak5rmHeFmPNjxVJSw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DcbycfNDfDIN,iv:3reLcPtaRV9q7ZwHsXhAdOW50gXPAiRHpMRG27DWDm0=,tag:vnBHQHDkRJasGuIrRwOThg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VUZ1TGJLSjhjNmNTanp4
            NnRMVGlKNXZtTm0yeHRuOUdjSmdEWkNCVzAwCkEzOGI1L1hoUVMxc1JnVFIyaUdi
            eVV4K1k5Z0pCeUczQ3R2bTdOOFZEUE0KLS0tIENHVGNQbysxVG1ZNy9jT0tLaWNO
            M013eTZ1TllBNVV1NlNRRFlzMXRnMzgKwzMHh/BpO118wyVVD+3eK/DRclKsyK9E
            s/qZl0Gi+RZ6CMmTCkxwApMuNmsE7jUDrEhSNJOX/prmITcOYDe+TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T22:59:14Z"
    mac: ENC[AES256_GCM,data:afgbxKZMve/oJL/55gZovwt4SY9cLiVnraUkD1SBMmLnUk5yBeFK+S95H18EDYDByCPro1V++ZYb3NPY99U678xuraB2o9ti38D/jutSY4JbO+ELsvCbpxLh2d9zn4rv8qPNvNIPf91SzPXKZAO1ers7ebSKYKayvb6SkFNkMfM=,iv:5jvUwYXadjnmzqRGrcyrzN1Kf09odp7vz4MLTM5G1dA=,tag:A7q2ocqgy2IJoz/ndKGw2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
