kind: ENC[AES256_GCM,data:0JzCDEus,iv:6tvPrvNjY2vZIcrt+vuJJHhffMjUxjkCvfT8o2xqBcU=,tag:XDeS53W/gv8fmrN8uvoy+g==,type:str]
ansible_user: ENC[AES256_GCM,data:F2v/NTjcGg==,iv:Xu8SvAUpzJxBtNnIIBxnsVlcUoSE5l+EO4mUSYCupwQ=,tag:UyYCPpFY6gG79OGpsKPCUg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XK6WomdHy3Qj,iv:Eg5x5s+r8UjO8lDsf4dvZKjuAs78Wnha/HBtPeF5+D8=,tag:4Bn0xi9qOl8g9XFdbOqphg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOTRERVdsRUpTRUtzZVYv
            akZGMFhGaC9XZEZ0NVBMN0U5cG1LUzlmSVV3CjV2Mjg2UDc0VXVMbUJCZ3pVekhM
            WDlJR0RXR2l6ZXJGTkhEZFRvY0NxSEkKLS0tIDNHMWRZUXpsOFkwQVdqRWdEbGJx
            SVcxVUNBOXhwd3QwZDJjejI3V0NSb3MKLYCIl+Kl45TF4aj7UBUaylbiy0t84dQ0
            jraRPl962GL+n4fmJMggRq4LRX59Yq/+S8Vi3RbwKpjH7I8PUK9JZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T04:33:28Z"
    mac: ENC[AES256_GCM,data:Arnyl+RS2po8TUI3NjKSfCxOuYnJ0ItPeNP6Ni09VByxqYYDRFbNtcaCGZqApUGY1qZAM/X64Hjir0nk4hloeCOk+Gc53pZbt9pI7CsroCK2KSwyOGY4bcSitM+AfT3Yu4tVqoJaalPakty33R2oEcDnqnrrZKfII5s1lJdwjUI=,iv:ksakbSGL+L4iTG0X2tDqtW9iCknfA/lKKYRkmZF6r7Y=,tag:Beb+88znmLztqy6gHmz57A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
