kind: ENC[AES256_GCM,data:jP517S4A,iv:JsdmJvNtWEzXhOLDyaCQcK5iSmq+SixRVlfqvzx/CnI=,tag:Rml8o4lH7w4YsH8QealrDg==,type:str]
ansible_user: ENC[AES256_GCM,data:8L4qEQDxNg==,iv:b+GMF/gOKZEieNdCxawcqSL6vOQnUQOtN++OyoBG5wQ=,tag:aDjF6czHoBN8dQbj4BAXbw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:A1CAUkNcitBI,iv:dgmYcb72IayXnivXxowr6FLkWdyNWwTGCHWIGoqMTD0=,tag:MqNFlF1e2scwhZsfMim8IA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb3hBL0l0YXZtNHYwbThP
            L2QwRE92RGxnbnV6L3NzQ1RrTjFFWjRLZDJjCm9vZW5UYXFkTVZibVRsU3JldTdQ
            USthditOb0tFY1BjYXhQOXJXVkM4K28KLS0tIGhQVkcxVWZ6NDZMekNOWW5jT0Ro
            UTR5YnJ4aVM0SDMzNGdrWU5mellnc0EKUptzqhrYwHfUaXDefrx9yIaDZLzfiU/k
            yHUHNVeDVMjmH9S5BccHpuziYvNDjSQHteSA1vvo9CDwDyH4lbe/qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T05:56:05Z"
    mac: ENC[AES256_GCM,data:v3Q4rm8lg2fL35I/lVgJSvRomi81z3EkWPJKHKNhq7Oxt8YmQj/up1WNpWR2S6A50DTjykCKw36Yd6v6z2vqD1ZtBzck+qnWjcOC1iJjVKlPok2OLWsUVlX3kstzdZ49mu4ZhJuwPviKgZzaY8sDah56v9d7tGrDV3thK7YUDqI=,iv:3CuMax0au6tG+LcTIyvNETUpR4WiXFt40WWEPWl+3dE=,tag:K9oWI31jnENFcjI9A0jN+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
