kind: ENC[AES256_GCM,data:1JgFjUTE,iv:gxUtKEp9jfpxqFvOw62eK4legioFlbSz0xgxDg5UWU8=,tag:8Gmr0QTjy9dO3/KeEcezFA==,type:str]
ansible_user: ENC[AES256_GCM,data:6r3mfzEhMA==,iv:3iZPLEWHns602cs7v/YSy69p95JtP6txYRi9NktBiiE=,tag:3d9PTKWl1ZaC3WIcJ1RjUw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LJ2dFLRQ3+O4,iv:ilbH37rGbAUGzzMi9v58rOdVZmZULhCsqX8ADa3qZ1s=,tag:fbKvJrEfn5bEM9JWQtfXJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UG9xNHNNN1YzNmdUano5
            YjJDSW1ISmhvbWFpbDRpeENVYU1UZXJ0MURBClVrWkRkL0ZxaVpDQ0RhRWxNZlNh
            czQyUEczZEVIMEl0ODgrdWtUbUYxT2cKLS0tIEt1TU54NjI3U3ZBK0gxTnFXS1BB
            MDFMZWhRdlV2NHp2Z0svNU44MU9jWVEK1vd8joWBGZjyEObXO+QWF0AYpVB3Ez6X
            aKpzGTmeb7aZHmRxnRXgXRr240TeITqQq+cApB0WX/3R/qlkUhKO7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T05:54:41Z"
    mac: ENC[AES256_GCM,data:R6AawzMasI3aA3rWs+gknGpMj+xjRZJbMJHrfSUP7tbD72gyqQjWg6GM/oCJNJOADssxcSDG1PWWHYCbZxXRZzsgtx7s4lfpyC3VzQWOFrE1USH7/CLOXKpx3T+5EydjE4Fi61Dn3mrYlvS6CJEyvwFk2IgI6oyTlOH0hBde/mI=,iv:ekn2GZ5GNwjmRnL75DuvbTQ6tSV/0Y5qlu9lf3CLZwg=,tag:z6L9hg1/PRDnn9UvviuAbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
