kind: ENC[AES256_GCM,data:hWJt11g+,iv:1WFgboI7EQxGWDR3GefGCzbEmq+hhDJoRajq+yxgzSQ=,tag:X6o5WwNCqeBJJs1wnLyYEw==,type:str]
ansible_user: ENC[AES256_GCM,data:pY06F91O+Q==,iv:0GO/IRVHuhdpmF+GCHWvFd1YXiO++PSLgwtPnnwkwgo=,tag:V6SZiM8lXGQVOEEyXAbZXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:A7deJdcj9XJH,iv:rBvtkfSRnF3/UJtvLdpqNbxKixqG7e1mv81CjRO0F6c=,tag:A8Cts9M1cObW2lXvIGfayQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTjJBQm16b0hxWjZMZlpK
            U1gycDRxTWtSVFB4c2t6U2NXZlVOd2N4QnhZCjdTbHYycjJLTlgyM29mQUVKYVZC
            TnEyZytsdWYrcUtuMUZKdDdmZnVmSlUKLS0tIG5zVzJRV3FTelR0M1AyUjF2ZUln
            NllrNVdCbnZWQ25wSUVqSUg1aTMyaVUKwkz9IZfoeSNFj4koWLOnTnQJqMyQaitd
            LXUBH+agWtj9CnWsmds0ldTgu9MqAmOgGRrKLO1RVppWFGZuJtzYRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:12:29Z"
    mac: ENC[AES256_GCM,data:9vlASL6LBcr4GdGDtgAGq0Xdtg8DBs5ImFf9o7aCZcF58iLyFqr6qZlBZg/QfCkL805LULcFZTQqo3K4C78T7sK0G/NxUGa6mWuBHAXcysUAiqWviuL8/ajzwfewHGMxUTTkkD9tsSo9tl0CCglJSmeHp3uOC9lrkytyT0EnlvM=,iv:F7iPBnaJSoF2B/AvP0NEkwfwsGzxtNZQBGl07JJUPRQ=,tag:8A0yZDXNdr1yQq/+lwP+Gg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
