kind: ENC[AES256_GCM,data:6pYDhxSn,iv:rAIStrkGfQ14hcOjsq/SvkRbLcF0Yu8YKTMiaifTUlA=,tag:vKFuVQ3PlDWRHOpHI9utCQ==,type:str]
ansible_user: ENC[AES256_GCM,data:hFNgJJsFVg==,iv:kszSr5hIfnHQ326x7R3K2fDO+rl85reruLGAPFWlp/Y=,tag:kHQcVI7qsizgwBphh6kloA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:b5JaGaMhmQqm,iv:jLS9Qu/FxK5oKYBJ9DjT9I22xxItWKFQguLppSeZusE=,tag:j39qj9Wu/RvvUmSMm0jJng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VWVXd2pGM2ovM09TRFBI
            VUJ3NU9mTCtKTURzd2RMZnNZdkozNVZqYmx3Clp2Y2F4SHpKVHlRbW1ZZ3liQjZm
            b2VKRFduMUpHUEQ3Sy9xck9Ja0MzUVUKLS0tIDRDdlRuSFpwdE9NUnhtaFdCUWta
            a2RXQ0FEWi8vWkppYm1ocHYxd1RFWk0Ke/5pAvXUOUpaF2mzZ4EXLRF3/BREdV3k
            uvWvOg0xuG7F6Ql2ppzMJnsYUmaSJFAd15XOG4lrTEImbUuA0KF9kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:39:57Z"
    mac: ENC[AES256_GCM,data:XRXkxm/dJ2S7XFhL1W7V7Q2/3lUBm+5bLjtMrfpt1HIoxL2bKn2NF4jyASjMCFOTxdb04pEhIqu6j9saLSwrjSQfkKkEE0qGDivWX9lYHbvBEZZnGNn1ZT3kVPITe1wwaKDSdWU4TJp3BzSFmG9ORff6BSWZA+4WxjwzE+Gq4AA=,iv:V7xzBxOjw9FpIruQXZcx8Ul86PpnE0AbsJ06U+34gtc=,tag:0+3RAgC1S98xFYWKSWpYog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
