kind: ENC[AES256_GCM,data:kqNoHQ6u,iv:+G/fSoQLVKcinOiUHxj/j3zhkT16TvidYiJiij9XMb0=,tag:Gff2qvzH7bc/N6WQLGLAqQ==,type:str]
ansible_user: ENC[AES256_GCM,data:FEI4Vtz02A==,iv:3TxBgmm8xKAM3cv7WbRJebKMGlnmsNIqGLZ9zdbpIqk=,tag:OQrw0FSyOuil6fHvNmOZ8Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PgUSDc/Dsriv,iv:uDAGUD3n7XYg2zK4IgxK0HcVC9U9qkxReG+2TwxHbJU=,tag:OVeisvBjHOQD2Q4JBs9Ahw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSFpZZjJRV1UzbHNyQVpZ
            Y0x5aHlxM2o2aUFPQ3VtdGlJdVVQNUxlUUJFCnBjTDRidXFiME5kWTFPcEI5SnRP
            dStvOHNQSDk4SE0rYjJQRTJXWExldVUKLS0tIHJLcjZBYzVMYS9ZMlZRNTJOS2lL
            NncrWStjdzZkM2FkMENYVFo4elB3bkEK+laBf4rfObYpjN5kVwu4MPppSo2gexkv
            iLIP/RJFbyZSsEdKoGBJXBdetYCY3OjlspBeaLGeGlk6sWlEIdR1kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T05:00:32Z"
    mac: ENC[AES256_GCM,data:41zeGJkSgifB+Y0lGZ5pegdy5/wR5heWkm3FoLPieca7siKf5jR4wUPSLHyT2cWmMN2K7FWMGv8py7neYvxBeylEhzq0sO5TE7w19xajsZ2r2TGwl1pEQ9Gd0O2gcoattOnEQG8UA3KdrsEHR//LuLFCMcQPV7MEsQ1/dGcBMGM=,iv:eKBjhe3iz+hYl0q6HxBQL1ZE2ph7E8/207XaVUtI8L4=,tag:p9aG5O6RmxgeQZR9Nz3HEg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
