kind: ENC[AES256_GCM,data:NjQEG7lO,iv:yAbDsKX3dSqJAGWD/i8w4CH8j5/At/VeoDLoGlcLmyY=,tag:gvgpkeDzv7t/IEFVtxPTWA==,type:str]
ansible_user: ENC[AES256_GCM,data:uvAdC2P8Qw==,iv:ZxVYtFHsFPoStTAsSWZnYfebqm2fX/G/5qBPxYMNrGo=,tag:cwvU064q8b8NPXsDQmBbYw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CkMtlLRAfv8v,iv:X8naKZ1azvBG5PUy2DjDEI8rYtdbk6UH9WY7Tk3Jh3I=,tag:Onbkyy9uOEi2FG8NXDM/QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc2krdGJKOEV5Sng3UENz
            aFBxWmtUZ2JWbWJ6M1d5ME5VQ0oyVlV3ZTBNClFvbk5sT0xSd0pNT3pmWFh1eUtN
            QUJtRFEweExoZkVxNkExZmJyU1RzNm8KLS0tIEowdlJ6akZSR1RJVHl3L3RXVnAy
            VUx6aVRjaUxZY2VhWVlyRTk4bUp1KzgKM8Nsxg5vOkKjtfJn60wvOajOSEWWe1EQ
            wM8foje/X8da+bMu8hkuCFR9zQiSAUwupUZIp/ut30rb5lxJ7UjJ5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T10:31:08Z"
    mac: ENC[AES256_GCM,data:yctNP7M/WyLb37+1UGTBIjG+wnZyHnTEX4fNLRjtY9xKYSrhNgWgoKXEiQqQPfSKkenqVLU4oStKwisS7VkKUsIqWCcwSAzF6dBwlKzyeNMvU/8HR4OwdCBb8NYF13cWOdFdw6Br7fk+SxjHSyPdW75Ba8KPgRQ7kFXJpQs4QSM=,iv:MGowa6YBnJbjwPBjF6fG3SZo9q53AGd1Rx81stGKW6Y=,tag:Y6UhCEbgDcI6e4pIOOETCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
