---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  resources:
    - kind: GitRepository
      name: flux-system
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
