---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-actions-runner-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/dev/actions-runner-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: actions-runner-controller
      namespace: dev
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-actions-runner-controller-runners
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-actions-runner-controller
  path: ./kubernetes/apps/dev/actions-runner-controller/runners
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
