apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/8IAAQoHGC7UM/TwRmtlWnK3oKw4lJjG1KEco8BNYV2LK0Fk6LoLdQ==,iv:6XRGpzyZ9beEEOyY5H6bQZeTNi3oRGpvrblgcA3TJJg=,tag:DNZM0NJa306TYNxSpkeA/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNjRNSDdidjlWZTdLQ1pI
            cURHV3lEMlluVzFhSC9raFVKMVpqR3hsQVFjCkxWZEQ0N3pXaXJ6T1EzVGRBWlVq
            aERIQUVqOGcrZlhTUGM0TEZJeGthc2cKLS0tIDJyQnlhOUs3ZERlNXZXM0U2clpD
            d0R1OGo3dEY5aU9XWTg0U1dTdVBEQmMKNVSVJh7fv37pLLzCg4lqIZYlqeH5RD6p
            L+a3wGf6q1k5WSE5xpDwEGtHYF6tP+50xuwmdNL2I5T7mmf7y05Xwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:12:29Z"
    mac: ENC[AES256_GCM,data:JE/2PVhIhfSf1J57OvhWGV8FDUP5cIDrybTuoWxdpVtmQzX4V0GBq6y+MIgDdEq8U1kjwR1CaAExb/m183sQRyN5EflYDe3/qhsMdIXGnDf9S6s3sE/X0hsv/sZt73vw9Du15NV3jjfo01fRsCYeHT/XAXYLMbPiy0n7rP/kYyI=,iv:hqWDQdBgxYK+jZ6RQAVjK0IQkVMMHAy+vruwfozgX4E=,tag:PMV6MYwaQkUSKCLzI0h1MA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
