apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LNZbclr4BSdUh0IsZDZV8OXxizdOzntXJNH0xHF4r+tLD4plr70k7g==,iv:3RgTbbGjyQ5RiTw63gNQvDW5FpOQzsENGTBmbni78Js=,tag:YRbh39OBW7JU98b+1obq4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZGF2cG02bkc5Ynl6bitH
            amVZZ09FNnBBZzdTamRsR0F1czNHbHQwVDNvCnA3RDFZSjBqTkpDSTQ5SzhtUXph
            SU9QVTcxYVFmM1NwV2JEL0NZYVFDQ1UKLS0tIEs3OFBFTTBZUVduSU82MENwYUk1
            Z1d2cGNld1p1SGcwN2RPcEhGdnhCeWMKgLBCDwtRQVx+ytyhXRlxkm5e9ZVPfY+S
            M7YhEHrNCpI+vF/VJjxMoo504DvsZl2S9Q2FhYbgu5WyYSMA7eTXPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-01T05:00:32Z"
    mac: ENC[AES256_GCM,data:imD/QgVbai9LxAS37BcCSaEpEr4BLoaRpMDOnZRmlrbrSArZ2AYTgbXVswyXmpvbrCG59Nzf8LdWRR7QozQvmpby5tgFhCUua44ikqg69EUEBmXKX08pqZwPX0qLKDUxaGS5ZPW/vxUN4v7fvRwiCMDSztd+rVpGduGJPSjKqsg=,iv:ZT8touwIQo3rQJtqIHpTaA6gvRGUd0xJFKCU1A+7WbQ=,tag:4RBVVvD6qRo5lscvN3gt0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
