apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:p6Zm0tyy++qUkjT1sUiuXlGYs1RurxWI6tT2Z5taHx43qHK+GrVc25u2DpCFKsEK4enz2L85/Glqv9v2irA/cg==,iv:VKq/sQH+KP5iNFqhHwh55fMKkBQE6jgr9RvDdIWVdbA=,tag:MGyEaSk/d5u0uv92g0Xhjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ekpoeVhudUwxK2tXblU4
            a2RHcGxoeFJDajlzUGFwUjlpNkFUd3ltUmpBClJoTmxPRHRxMkZtRE9aWVc4R3h5
            bm9ibjcvZEpOOGRKa3NpSUVoeGVhNkEKLS0tIHY1WnJjdEtieHVVYmdJZHpTNjIw
            Sk1lSXpoSGpaQjN2ZFRLRVltYmZiY3MKUkrXZ2NrwH+ukgn2TqUtEuZjAURMUzQ4
            cHNkS9tjlDMoUumTZBOSA98yvVhudLCmqi100o+tRxq2IiXJK/SU8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T22:59:14Z"
    mac: ENC[AES256_GCM,data:esd5Ggf/dwcrPFlqJipByYjMGYcnDOK7CD73XJKQ70ajdFweCWI5NidGUettgOvb+sgk8o3r5py2VmtpC1aA0ePzUiPS7acmdBqVRLldVaLIohBhyHxHtACeO/4mUIVVHJT0g9DdAOx1qwPNe1xJ7p7AS8pYkQzwWDHbYuCplF0=,iv:QmFB1GuHlgjX7wQK5qYLHWAPteCmbOUoMlAhfpPHLvc=,tag:fhMzmqJGfdf4IzlPwByVmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
