---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-java
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    extraEnv:
      ENFORCE_WHITELIST: TRUE
    minecraftServer:
      eula: true
      whitelist: lethek
      ops: lethek
      defaultPermission: member
      onlineMode: true
      playerIdleTimeout: 0
      maxPlayers: 10
      tickDistance: 4
      viewDistance: 20
      serverName: SMMX
      levelName: Survival
      levelType: DEFAULT
      difficulty: easy
      gameMode: survival
      cheats: false
      serviceType: LoadBalancer
      loadBalancerIP: "${LB_MINECRAFT_JE_ADDR}"
    # persistence:
    #   dataDir:
    #     enabled: true
    #     storageClass: longhorn
    #     Size: 5Gi
