---
kubernetes:
  children:
    master:
      hosts:
        nc1:
          ansible_host: 10.0.0.21
        nc2:
          ansible_host: 10.0.0.22
        nc3:
          ansible_host: 10.0.0.23
    worker:
      hosts:
        nc4:
          ansible_host: 10.0.0.24
        nc5:
          ansible_host: 10.0.0.25
