---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-nas-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ingress-nginx
  path: ./kubernetes/apps/networking/nas/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
