apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/overseerr
      tag: latest
    env:
      TZ: "${DEFAULT_TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
        hosts:
          - host: overseerr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: overseerr-tls
            hosts:
              - overseerr.${SECRET_DOMAIN}
      api:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: overseerr.${SECRET_DOMAIN}
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - secretName: overseerr-tls
            hosts:
              - overseerr.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: "1Gi"
        mountPath: /config
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
