---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: home
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: home
subsets:
- addresses:
  - ip: 10.0.0.200
  ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: home
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - secretName: unifi-tls
    hosts:
    - unifi.lethek.net
  rules:
  - host: unifi.lethek.net
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: unifi
            port:
              number: 443
