apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:vq+sVQ6+0uIeydM2KvGOaBPy3rj3CyI4blSNfLQPA5VNii1ncw==,iv:xsw6EA5vuz2vFmv68lVHCrn8xJW0YHbs8yD+S/gdH8U=,tag:2//G3p2CXQ2y6z70NZJ+bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza3ZHZjMrN09iTm5TdHZW
            cXE3Z3pxUHdZMXl6aG5FNFcvVC9mb0lvd0ZRCmF2QjdRNlR4OGo3ZVpvelo0YWFx
            UHNOdFhZYkZVdEZaT3p0d09IenltcDgKLS0tIDhia0h4SGtLTEFxNWpwaWRXcmRv
            QnFsNlhxWWpvZ2RvSzNCZ2FkWUx0SHMK7IrSCjtmo9HjCXj7lhAhoCpagGQUL+Ry
            NK9HKO3c0TTjg0D7cVDSLsZ+mD4s/noX70s4GrtOh4flJgQLn4bZqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:39:57Z"
    mac: ENC[AES256_GCM,data:g0NhGBa9tarQ1pFypoqLLES+eqNi+21LLQadbH6oE6UoKfeqh70GOq/aZd5ONOVXereeoRJPeJmx8LOmP3OZFWru4qeEcT/Leynjwa1AFmRPLWHBtKmdU0djiVcXbJT5Y84miXOBw+Z5Uf2nsGJLgOZ0wSzTygxuYsfdVQ8QriI=,iv:m8Z1nf1oukNTTQ1MFNorzKhjlFi6GdNo4TecwK3vCqE=,tag:eHJdn7pX/+kHFKG0AZYScQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
