kind: Secret
ansible_user: ENC[AES256_GCM,data:SprSG5R4XQ==,iv:EpMMojudDe15+Fzd4/mshdxc0QkMnTc2BarQohM4z14=,tag:75LCpstX6eNI0j3mVqGQ4A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:lLBPHHiOYQxo,iv:YMfTPaDZQPHhgZx6mcKzOT6lS0pyvUOpWk8F2uNiEO0=,tag:IWHReaCf+pjNEPO2hrFYig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWJXUDlneFoyVDBqNkhl
            RUtwd2ZqcTdKR1ZranArajVYMStPSVJzOGpnCnVqcVRBODliUEdFcTdFc00rVHZU
            VnpCMVZDVkJ3WHBkQlFIdFdLLzNSdFUKLS0tIEV6MDRKZGtjb3pCQ3FDVGV5eUZI
            NlVzVmRyVE0rT2xJcFVUelJNTFRxMkUKbgRm1mPn4g0YoLAQiweTTAILr6sd5WRW
            nqVhezmmWJl1zKlMvZDFntxWgYdToPoe5xzNBpn1PwBV/oyf+UKpfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T02:02:39Z"
    mac: ENC[AES256_GCM,data:2e4KeHFPboxEpkArAPXIFuHpKZ9hItJr+aXYDFFIA6bpV9UGze+Cor+5zXOP0dpNHqFjuLeUcBtPMUqdOX3I1Q4PtgaAgZyPM0lW2afLn3fn833VzvhT73glPHEz6H8X+P/hGGYIIaODy79hZ1n4FPtFEFI38I0V5R3wdndw1AU=,iv:/d214ed8qYTFJd9yPl/KWA0beSXlBBRTn8gDkGXMJsE=,tag:DUrJRxjdJ01ThEaKj4ma+w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
