kind: Secret
ansible_user: ENC[AES256_GCM,data:F1WjaKYTPg==,iv:mbrvj+yHEAEp8GMTPUJMQ2hBv7mXsouIyqWGJEqFHyw=,tag:kWOXT/YWZhnKHcLQxKEBcg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BEeTAsqlDNqm,iv:XRPWSlMFy0VKCa0/nj1cvAjVlJApHob73EB/mP5WcKA=,tag:+zSEphfQZcXzre9F+Tuqxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q0VUcE5rdnI4N1ovWU9s
            SFNKN3F3SjJjK3M3cUljT2hGbDlZSTJvSUJjCk1YZUhIUnpJYlZTLzB5eXVvLzE5
            SzhxOGs2cHJocWI0WlIydVpJY0Q3djQKLS0tIHJxU0pqaE9tVlJzZjVOMlZPb1ZS
            Tkw1REhCc2ZPcW1ZRE10T202cGhtNWMKGiP7FKdLZtZG8fqBAGFWtz1C5e1NCVTt
            SySSgGKCQCffqQOAle6B74pJZU6x/bwO+9hIEuDkQBm3iPmL4iN4oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:19:11Z"
    mac: ENC[AES256_GCM,data:BdXxY/oDYSlFKabQNxLx22f3iAbNNooYN4p8DnFoYVEbD7c+v2cTD74I1b3ENezh67gaJq/aBYbmDHSu0ANI3s2NyoQ/fpYTD8W7BQ0savf7zl4TS+7u7gi2Jqzp80x7ZsFIuMD5lhkIC84Vr9n3sGEQBzaMsdn8MjwSKmeauO4=,iv:gg6Bb1Fsfr25hsxlE3ezjhVglJZPiqAyS0nU8EZp5qY=,tag:B3Ni+uvX2bZy9ooE+hKYmQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
