kind: Secret
ansible_user: ENC[AES256_GCM,data:j/778a8KZw==,iv:EKbSpggNYh3XGRpA8B4LrhwcvuU1QdQUmpp9aPhCUgg=,tag:5mS7GIRqQYtWIylMAX2u+A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:55HuJuagSbZm,iv:rvr2SxJTbE0a90ZzbHyhbAxVPjIG/S4ydUzt0+DupVY=,tag:14BNKwlHhPVdkHJLi0AUSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdDUrckJ0WUlKa2NQZm45
            VmlrUFN3TVZRbU96dU9mY3ZiclYzTU1EeTNrCk12ZWxaMzNZaHpaVDNReVRCOWZp
            UDhvS3hSK01qZzhxdUMrN01UZlV6aEEKLS0tIHkrSEpvNXpPN2ZnNWdiRUtLSURO
            Mkd5RnNLSG14Vm9kYXczMUdnSWpIMU0KOxECjK/hXa5Oz97tIpbrQIPHekfJfsQP
            sE8Y+oXTtQ6AozRH8Pi5Ka5dTv2W6pwcH8km5v1h4VgmI3SEJLVSeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T05:04:29Z"
    mac: ENC[AES256_GCM,data:DiEiJmLgB36uZs2z7+Z2B4SZAix1bKCsVFb3DVssJ+Uox5MM+mmBYFm+2LBobxLlEtvdGOdndZUN2fNI1KD0bDMvWE7Uc0Cqj1VfT++adHRlbY2T0W+bx7RWWAsn5uSoCD86DSYW+bynTjxdKZ55d1Bvl45aSRT4qgtKtpIr6xk=,iv:NPL1nRtclWK9IsYeht7KFl6oj8bst3Lh/5bqpE71EoQ=,tag:9gPvWpIEGRiw65rR2PGlkA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
