kind: Secret
ansible_user: ENC[AES256_GCM,data:wWYoIhlDgQ==,iv:lnjHSjouVYd6luNqfvLsesTNpjs8M7PwS5htaLzaYLU=,tag:45biju6K/11tM6bbSkB9Sg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QrHzG/REfn8d,iv:JFll5E+0MHwB5v17j4HuIRXOHaewgWEJs4JNP3hODoQ=,tag:pIglp0nf7TohbSVGBOiorA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwajdYQ20vTDQ4Ym4zT3FZ
            Wm1LSW1CdmFQUkpjMC9WeHhHK3FycjJsTENzCjYrZU1HQ2IxVjV6UjB5cURZMVN5
            R1JBYmkwTXhCOUNpaUs2K0M1WmZiM0UKLS0tIDVGMGhTL2UzK1QvMmVMS1JGYjlO
            blhrWVJpWmJHV0hTaGorNDR1eDd0ZTQKxxQaI9w30lbNliHopSQo9DanbR6JRVpc
            Qp4vAQWbZ3K/D0WhRevBeNaRvhlIbTlAaUyXpyfU4cS9JZs31qACsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-20T04:21:21Z"
    mac: ENC[AES256_GCM,data:LYvz8t8jRl6YwaVAk/gh+rnCXXy+Lah/hhWO80UQMVks4k4chOsx5cX0X5Mtp2WO8WEJCT3gKIJ2rjhKu9D7eiA8YC01ipmX04FHhvKtOlqAXsF8uUsmfh7BxHzQxIe2YTugpw9+YsNkNSs5PHVNuKrtx+7w7vIA2yCN/gBV6oM=,iv:bR5wkzgkAzf6KmsJpKsRxJ+7O5U84T2O0cyNTPYDe5s=,tag:rgnD6evIO3bPXMaJyLTNVA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
