kind: Secret
ansible_user: ENC[AES256_GCM,data:zjGOfRBwLg==,iv:aUh7kDtmIuqArsLoq4WeI1xCeJq7BnCNNKKr+pAznqg=,tag:VWGOaGISOle3O0SFRUo9Cw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:e2UeZQOmtUjz,iv:C9lzM68TeXTL9TRM6yRI4rIaXjfL5u4W61pTcQQz66g=,tag:5TGMWTzsIQXP5w7gIydL8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJODZ5a2V6c0tUNDI3dUxp
            cUFrTDNpbnFqdEp2aU5rNlFJUkMxdEVMdGdRCi9KSXc4WUJVc2MrMFp1UVJsc3dN
            NFhqa09saWtsMlcrclU0WUJURnB4cU0KLS0tIGxKa1ZQZnVRZlp4dk51d09PY3Bi
            aGxSTzlaREI4aHVld0JDRktJUXpkOTAKxpzmmoreBqbO+yZsQbabOyIgw1UyhLTA
            y8jyT7ZcSn34Zb2rAbWINGInr4Hpb9B3C4Noz7qv4noSOfQ8Nc0ERw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T22:51:36Z"
    mac: ENC[AES256_GCM,data:PZykcLY2Xg47Du6HE6ytq+vMqSyNVOTKvVAzR5myRBeYYjNVYb0MPaDVkXs2m/3k7Rb+LoT0Lu/qr3O7Z9f8SkwC3vP2Nhp022ngznosg3SerWyUTehYS9d9Pz7UoOCg8CY5RQ59PxD2UyFENeE6rrv0EPNPZx1+j78tKuiTujE=,iv:rfcFCv5z2eGqTisFqdX8GF8hTYOtnyeoAFyMImQPws0=,tag:fJGbUbxlagFzYNOzU4lnbA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
