kind: Secret
ansible_user: ENC[AES256_GCM,data:PYmYdq5ILQ==,iv:sb31SUyXto3hftVhwWF5XYPjdpsYIsLFU1iRZbWkuHs=,tag:Vx9r2f7rS0wstA/XBvHRSg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BwL7FbP9Fi0z,iv:DKRcd3qNXTgfCQk8ZxiWEqMrAj7rxnqZasXZYaioz4Y=,tag:pZOQ3D0dyshhOq+YNvVVJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERU9Va2ZUYjZXTms1eWRF
            UXhmVkhyMXZPV1QvVFZtL1BzSTZXeXJScW1ZCm92ZWZNdThlTWEvMlZTWkhsRndR
            bGphZmFUUDZqWVJjOXl0aDVoeGpNREEKLS0tIDRvN0o3UitaYitZdWFmU3B1YWEv
            eVM1eWRxRmdhQUJOLzhlRWJmZFFoY3cKL6oQGGJQbQIuiMXixNo5S8AAGkUDTvrz
            GfoLyt4GtL6U6mRDX87EkyWJBPdke2W73Vr2PJkyOvz9/a6ePdxLXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:19:11Z"
    mac: ENC[AES256_GCM,data:FK1HY5j1vDfSejGQlt+PIzMMzlByILUj3RUqYrWX+SO8Hns6sw0KjVqIlU3VfhB0h46V4e7yo41VgLqLJhULRtTAt+pa3uUtJ0nEfhV6KYV5pJmTemMzxpEwKK2sZHX/xfzWIsRx839vy+JD1/fkd02i1+/51OzPBi4bFFj/dv8=,iv:hNS5vAfFqkTo+7lDYOceHYKbS1D8yQn4UDtSHh3eT+A=,tag:Oko6Qcc55L/BbTsfHiKKIQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
