kind: Secret
ansible_user: ENC[AES256_GCM,data:1U0Q1CqSlg==,iv:rmPmaNy7kclSlrCURxLaqHD9dbTrAb6IUW3H2VW9zvw=,tag:sOsP2Zfx+hX5j8ZlttkCHQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:alzR51GmqdLP,iv:L4+C86DvQTRAoby246bdTfWTwQ64fgr6YHQOtWCvM3o=,tag:VyzjBORgCur6IxZncmbLEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENjlsaWV3eVFQNUFsTHph
            ZWhhbVF5Z0NOMEkwWmhKZ3FXdlNuSTFzL2dBCjM0RmEvZStZd3lPd0pKblg3MTIy
            VWNzUjV3RjAxS09IUFI5MWRUa29yUzQKLS0tIHlXQ01XWHNFSUE1NENHWU9VMTk1
            YjhFc1pVTzNSMHhrMElEVXc0L0pSdFkKEwH5u1R2637+I5HOaPGU0hM0zeJ85M+G
            ydFX7rvLXsZiCzEsF53LO+pnIUEcOTNk0R2K4bodPEx7dnKQ4c5rLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-02T04:40:28Z"
    mac: ENC[AES256_GCM,data:DJ9+rnAeoVVCmMxiKzbNkMbNwXv9rzAr7yvT7KkvzHmYglqpV43O8lsAwCgg8Piw019i7YS51fHXF+44CO2o2JqiG6TQz6WW4uHWFzyh8BSsaEm/jswYd5UzgtzT+4toOWhcXqkHiEFSex77n6kHrx6b7rB0LCl5yhLXPCZOGKw=,iv:e9zYE0iLmpXc/gpYiebEvGY9a6Eq0EE2gKarQS7pg34=,tag:i9brqvNlZ1sW+5GeogWV9g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
