kind: Secret
ansible_user: ENC[AES256_GCM,data:CQYM4yfxAA==,iv:ZW4jGmY/x3SR5ZVXUF7OJdS2m2VX/p7GnZEGE9WDQ4w=,tag:Bys33Pf17uqxoSIn4Bo+ZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QOSEcMxCSryh,iv:T3PYQdrI8momxWR7CIhnfrBd+NLEMofscqECFC/HvRY=,tag:Dm9JUECGBVq3B4JV289WzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUldJaThHbkdyMDRRR2RM
            RFFsNVZHQU1ETXFpRkNZRkhLc295cmFEMndRCjlyTkhrYmdvTkwwb2orYUJRYUVQ
            K2VSbHRiY2RsZGp6MGNUdmxIbFFTNlUKLS0tIFViYjFXN1Q0R1pySUkrRm93T0lZ
            dms3OXJWbkVVN0RtRStZeHNJWjhYS1EKY7LINWp98c315vAOijnfXA5dYjzc9UH5
            8X8ytmOZq/M1tpw6XS95kjh16fy2zY2uCPmJfoQbpya1BkbZSqWQsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-21T01:05:14Z"
    mac: ENC[AES256_GCM,data:/i7e/oXCOzuH/QZ+TrE+RJvd1BeijYaleXvpPkTq36lgSNUujym0+dWeizOTp/YDllAhhJLHjSJ6U3GSnBX4jee/+DEhSMgAG/87hRMMVb16Wp0DSTU9ARlLBUxGWP2D+Q4P3/EijzEykqzUPiAcSAInMN3qoIqJTFZ4BRMz4HA=,iv:I5/YWNYINFKOj06I1keAGydA0jrXu80de8N6T81ca28=,tag:e6KrotV6gZDnYJn7+h+MRQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
