kind: Secret
ansible_user: ENC[AES256_GCM,data:IeWgfsg0OQ==,iv:mCWn8FUcIhpJn1I1SImNqpWczRSW2bHABRlZIgUS7Ew=,tag:IrdVJ1yGkMvXgPd8Evw+jQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:punZHlxsQWMf,iv:Bd6tJpEy2uvOt0jH2ivnOwEj7lTq476R77cRLcKGXHw=,tag:0y+Rye0dHyX1HxKwE9kOtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSWZjdlV4VmJLck9XUWZB
            bFNUL0ZEWkZ0QkROZVZjRTl2bFpRS0JyYkJRCjRKN1dEUU9UdWpnVCtEazlQbW9R
            T2pMbmxEdys1U2hKcWhXSUo5SFBjRTgKLS0tIDlacGgyRUF2cVZ5Z1hrdFozVHIr
            VTlHR2JTVUNFUU9uSWt6K0ZnSE5LcXcKxjyY+CKcyfs0OBh8PfzQD2GMII/CWHxF
            twRUXG9NTW0WD96i/bgmVf3VI/l4GpbOcLOmw50rG9hYJGaNk93Tsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T02:02:39Z"
    mac: ENC[AES256_GCM,data:kVaRXi9e/o6/PhH/iI0InTC5dJtLc+DJAqM6GljmC09XrOx6zED/pLuN0ps9qwruRMR2OP9I2fSuTZPfi4XDCfANCVTeNUAjcgs/9WpsjOxGFFo2cwqhahjdaouP3KigLFSHK3+ftcCGUakyN2X/TlDJ3Ujy5Y03fSTc3F0I20U=,iv:ut59G1jag+o3/2X+D4pb2+Sm+7OFTbc10QKvxgXNePA=,tag:SO0cleKq+f4pGgBfSUf3Tg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
