kind: Secret
ansible_user: ENC[AES256_GCM,data:4OBr8Pd0aw==,iv:nCtq0A0TNih0iBzB0IdDeZHUcZE8coJBYaU/YmzfFBQ=,tag:0pNs6CFIJJpWcw/z8liVdA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+HsWJ61dthK9,iv:VL/Nktk243qR8Rbyx9QnbRU+RU47zXxwtZgKFUyCBRc=,tag:ivUqi/y6/RGVi+4CBBnNpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWlNXVkxLMHBiWUhwam1s
            SUt6RnRoa2VyOWhVaWxrV0VYdTlGMHVZSFNrCnkyeEpKOWpXNHdJcUJza2F3RFNG
            Z3hJOFo4WWc2VlZIQ3RlNWxMTFU1eXcKLS0tIERCNS8vMFlFRUNiN0crc25aSWZp
            dkhsenlMcGpTUEU0TDNsVkluQktxYmsK0N/iIaVBW6S0qVsad+00dWKiShh+wBCM
            lRrtCrPZWT0lH+GUFcTcznZkFQU62KOZ0DZJY5Y9gaMw9ukLIJqb9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:19:11Z"
    mac: ENC[AES256_GCM,data:n8Cu/nrUGUMTCM2SEn2tZOPMIBN9hdnGkZ8Di/ASzRWORtVW3Zorf5vIuQVyxNn/R66wp/zMnnq09oD34XLAxPVx4pS+H7THuLiWplfCh25jDFiAB6iCOq6tpyWnacQxsoIo+pNT7180fXoBoMdG9LkzV96hHyXJ5D1mjlI+4eg=,iv:5sDKNChu+x+uwvtMoxSrELdoclvhavaLvlLtq4+4ZFg=,tag:RR78FNxS+0DjmLV0DvLD3Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
