kind: Secret
ansible_user: ENC[AES256_GCM,data:uuPrIg5nNQ==,iv:h6HPq/kodVEtrWHwmiQAj9OjAXmndmCpvPQNHfXNVVc=,tag:Qee385uTeFUSLga8Y5g1Cg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:e6C8NAdBe708,iv:wxQl9qjo0dGvm/LDsbpwY2Aasjd3mQOmWQRG1Yo2nYY=,tag:I2t0RFSyjcoCxeiHP45sQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRzVRNk5ndHV2OFc1ajRq
            ZnZ2QVIrQnhrZ01WN0lVYVVYNjM4ZjlHVnlFCmlKd0UyWnkxUVlPLzBXcWhIejJE
            WlFuWXJhT2ZIY0pDWGNKd2IyWU16RjQKLS0tIEczWHVzZ0l0ZktJeWhnMjJQem9H
            d0Z4RE0reS9vRTBMcWx2WlVHYjBaSFkKR/96WP/pAYHq6tfnqvX4gFPcB8oMyniV
            fts57uNq0dtDiRJw4W3LlZmBY1XrZXdp3ckiDDFz2Q/+23w8XEeYNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-22T04:25:51Z"
    mac: ENC[AES256_GCM,data:jXni9qrJ1o7yyYu+uiX7XQq9AbJigjYivbqaRyPQf3XFwPl3Emqc3Vldlls2RDd6QWON1Z9fzJQnQjL572vi5W9RiGKusYnaLHunP3vLWt/IZZ/ZoiDDbHQndPekphmsLeXkBEKQRuw0VXY3t0NcghaWWFg6ZCXdxHujyrXV4pE=,iv:OZT/CZwBJ5j35lNhZypICOnLuq2auqpZ9mKgbbmTMtU=,tag:y2S8KkIl631mbqsOIu5gOg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
