kind: Secret
ansible_user: ENC[AES256_GCM,data:sLhW3ZA4aw==,iv:MVFkmcfcareHXlGFQmV/vppobz88zjhRKnW7nauTA/A=,tag:45EnuquQuk0/lmdFfrSHxQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WWy5Ohm+6RQx,iv:flXiYvBvIcjtL6kEPRptFxbi0n0xWrD5dreR4rOTosw=,tag:/qpy5sQgvOHEuoVL85Fn5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU1BDZkJoUjB3VFE4TTc2
            d0JnSjZXQmVVeDdKYnlxK3VKZSt2YjBnaVdRCmo1YzN1TklqbGgrUWJuM0pTMkJR
            NWhQQW5oMjhtSXF2UWxaOWlnakxveEkKLS0tIFIrN2VvVDRrN2haSU85Q29CUTVH
            azA3VnZQTXBySlk2SnpIWFJ3ZnQyWncKYvlpHXiJA3eQNK4CMywZm9uTDkmCBEnh
            EIJTjJ1sgqTM2xFvrNbMS2/17rHukSfSCxZzG0xKKhUG04Yolet5Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T01:56:23Z"
    mac: ENC[AES256_GCM,data:MGScdzwdlSbD9+27102tns97VriSL3lCP/sIGCdCefgOHYRh2suAF14G1qkB+1safW2NGNb9Pho5itjwxI29hzc/HLFavdNzX+F9IcRk5iToJ6mOpLKv4O2X8JH4nXiITk91Vagu36SVlynzEUF55F7/wmtrXADklv0ihZBQ3+U=,iv:sEhruIUgUYxpNl+1b9DZGBfMj2apO5NBjyz5pAb+a7g=,tag:Whu03F82hYJbwJ7RCsjigA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
