kind: Secret
ansible_user: ENC[AES256_GCM,data:gb4SNPyelw==,iv:haZ8x6L9ZF16922P/z4VtEMnwFC+kXZgR6GRbMj5p/w=,tag:qYasrvjIeN06CCJhgsyfxg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PSm3x1rv4l1k,iv:Fo05abw+vnyjook8gu6CrfwpEUXN7PNeAIXgcFlzkDw=,tag:V/2rn9dQuSgUdL2NC8tFVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRFJmdEdITW1Rc01NN25x
            OG82R2JJcEJycjFnRml5eTZPL1JjTGZKcVQ0Clp0eEExS3A1MTNBd2d6akNsWGNB
            dUxuTTNxWThLdmpmcWg3ZW42dUEzajgKLS0tIENGanVaK2NaYVRtd0ZaS1FDWEdw
            dTR6Vlp0OVBOSWYySmJVcnNNL25mMWMKm/tACIvn/zBpDsmmExTDr7Ezn3S5ggJS
            6CDP8Q5T5zZpzs0erOUrWAH6ykW5ZDX8QCMUcRrBJNAiuYkkf08kug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:14:41Z"
    mac: ENC[AES256_GCM,data:W87j+lvgTE6JZK6vrHNayxDdM/I1SrjfgyRRNW6NrkBXqRulxwNuoGlX3MIJRpn2rFUeo4owQ58eRtSsLZvJ3nbeQhBkO8NjGDiHXK+3HB8yOU55etaqdD8nhUCiHplNc5AVtxcKdhvs5w2huoIcyhNC4ePu7EMnyVvaFIaI6Fk=,iv:ncNx4kHoT76zMLY9jctCDqsdWKXrQYKBXpu/Ke4NMrQ=,tag:r54aNfB8c7VUWswvEKFyNA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
