kind: Secret
ansible_user: ENC[AES256_GCM,data:htY+NBSRJg==,iv:Rhc0OcBCOJ/JX+BQD3kUOC1aspr7krd4c9HKVv1tfvA=,tag:kl3843LNHXTWmRzGT6qGJw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:v2cupyDK0Nsk,iv:5v7X+nNwbEjq3gBZY64d/I6dDyfAfUwJM1QxIk5I0Ic=,tag:HuCr0Zo3lTOIk/mSMGVajA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZHlKbGErNEpBd1UwS3dI
            QjZ2Q3JqUWdCaDdjbHQ3N3JrT2d2UXg3b2lnCjNpeGJkU2J6RlpYekRscURMU0xQ
            UWtoZURkSWtENFMzc1MvWGJnS2hjbUEKLS0tIGdIUXg5V240NzlJZ20zUVVMek9P
            NTl0UTJvYUdHZmJDSXZFVVhUV2lNU2MKIRiESS0OH2PLRcvSXS789OOvUmEZF6Yc
            ekODR6aoZFfd0efQkXFKNK8LFmJV73h984fI61F0ZyZKW60VM6lHUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T04:20:44Z"
    mac: ENC[AES256_GCM,data:k01TO2L8aDxjqYF+F1YrmLt/AdgCuWGGm1vShfR1T6RWCtFNrw9sgF3EENpRqKnTAM7OCWZy3aH2pHR6O2GJjlTHqoCbftWCUxWhm9wrkPjjHmrBYqFzOhvVrS2hub2xYenxRb79Zj2TPqRp9npXUSsNUGCd+aqP3eG8kg/NtJc=,iv:xkYPoG+P2ZbYiDNuPH1KFL0wYgLlKXhb3xu+z/SekUc=,tag:YGwzP8wexzZHW3jI3aa5Yw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
