kind: Secret
ansible_user: ENC[AES256_GCM,data:UET1VaNyWg==,iv:uzlU6k7k56rTWOkhR5M1qOuyLrVMgJH+c7lgPPzxryM=,tag:06qxcpXpm1POo5OevuvrnA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FEqablt0Jm6m,iv:7KgAibfmCcxaqBPxJYwJmb5OLteeyWoyHI7bR+ja8gE=,tag:OVNt3P9WsJYy4RJZ1r8svw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZkVqM0dINnNrbEYxT1ov
            aFUxZm1lTG82M3dRNGtGMW5mcUNqM3NaSml3CjlRNjgxbkN1Wlg0Zk8vRFZQNk9F
            YXNHdkQ4Um52VFhaS1hVMmFyMk1Ya1UKLS0tIGFNbkFlTnF3WnpYR3ZCOWNBenAx
            VVNkS3AwTWdaZjhNSWJvUUMrS21TRmsKQx91ai8mW8CMal/bMSDKqm5kOS0qFD2D
            Y7EhWdgdlitj4Ta/8hnUh2g56Hc6fo25loeSxOLUyF3B3EbISsvT6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T05:12:03Z"
    mac: ENC[AES256_GCM,data:rPy++xkP8ngOkIA4XiFFVgCHzM1KxYK/qcOHIGkRav8C/h8smizXTbMdva2qrHlJpxEpaHnfKmG5gl5aD7bEk0/EIcYyZUzk63ysvAhDBOKAv5hUAtqDnNZHMZFZlHr5pKWey369kj/hevRjf1zVIN5OI9RPIVCGOyWQozbxw60=,iv:y/CCUbaq6IT42uJDT+Q6g6IlNZsWob8mQzJx9dYoYJQ=,tag:EoczGfOlOsgtRvcAxvYzOQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
