kind: Secret
ansible_user: ENC[AES256_GCM,data:QwWDRr77zg==,iv:PZRc1VqFj8QwfvXyCjnn2jLa5R9ynUuFjXSy4f4bZzs=,tag:qdB7MxXK75O5M6/bT6UMJg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KS8Bjvl8dPXg,iv:3pvNX6RFP9Gkcw2Wr78BQokjtxa9bgfDB5eqnR94U8g=,tag:fidKU2Hp5xAYreywwCmg2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WXJGVUNONHJ5NEtXcXp2
            V21DSmgwUENKaGhUbWtPcWZOVS91VXN1K1NzCitZMzNaeUZabWxnZ3VWbXU0K2cy
            aG5LajZzaGhYVUhlZENGTUFKaXEwczAKLS0tIGJJbWVyZ0tkOU04TEFHbE9DUkpo
            UFFxWmlUV1VYSUQreVJDQTBWcnAyTlUK+AmW7FBiSDewO6PrwfwqHjLsm2487S0J
            UgLpyLldQ6bu4pR0zUHhiLMO9oqEiwBdy+Behxh0d4gjp4gHxPhevw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:14:41Z"
    mac: ENC[AES256_GCM,data:r+4Lb/bxnpTp1oapTe7SqKKzyu3Q9DNMV+pLbfhbH01hl2wr/fTRVKTHtBpO6NYpCsiMg2vsB1y+y9SmNQX0OgZzxWamsQlTJV9s1XFHnizZ2mLVt4XPB+Yb9uFfyQUNf/Lvl41lTlMtalf1zp56E3G/eKSgp5uKYEjm4aETSMk=,iv:xcXGt+UIEy2vu3XiUviAYyNo3BH+aotOZuYppqQG86g=,tag:LtvIsv7c1f+wpUt9ct4zGg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
