apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:VZ/H4clAYF/WeB3rFeQvxvhJ,iv:uXw/KvQzybEEdf0v91/H6EZcDfS5tPYBKIlMFxNBUoM=,tag:mUGmjza3CeNtNnAoOcisSw==,type:str]
    api-key: ENC[AES256_GCM,data:teOhQKywfGXVKdG8X4a0QR1CAkQTC/r0nc7Jo5XBW17ggbIW2g==,iv:Sg993ZgUUAHKqCGsp6A2cqzhVNpYkYF0KzgkxootZC8=,tag:R92a1MFnuPCcooTUb0J0Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT0hYM1pqMjBsQkVWR1VI
            TUFzcnFFQlRIT2E0VmhRL0phdW5pS2svVGtVCmxBbjVzalAvMjFJQklhMDhienha
            T3J1THJwbE5ieEVWSnNnb1l2bGxWMlEKLS0tIDFBYitjVmZwSDJ1YnJkcVovVUg0
            OVZoZkRnUEZ6dHlKU3lYLzl4cVc1NUUKJRbBLsI8nVHQz5l1/qyIT4rcDiPpwNoJ
            riZtKA/bUsMR/i3o5E4xh9jSt9q9GpAbXEWmHXFNT+M/AVZRZ9V4Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:12:29Z"
    mac: ENC[AES256_GCM,data:wqcPVSKPeMVXL2/Tf2GlOoufJca+dmMUJzTGFcVaTA+yIKVuot8S0PaAgMq0va1ke+a6D4b/jVDhqQdzHfWfKF9makawrKkN5AW3Gcf2r8saDAbvHX8Jpl0jfGOujvjGrZ9NkyBLbBrZ1t8bdnHU44KG69ecRlkOrh7Ll+7dgfA=,iv:EynDxdAWsU5H0MZ7BmJwxqA9wgaaC8c7OAYCotKiOWA=,tag:ibGeiHt4GFZ814EQOhTWGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
