---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: dev
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    type: FileStore
    fileStore:
      claimName: nfs-backups-k10-pvc
      path: dev
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
