---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: v15.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/radarr
      tag: latest
    env:
      TZ: "Australia/Brisbane"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          #traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "filmstrip"
        hosts:
        - host: radarr.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: radarr-tls
          hosts:
          - radarr.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: "1Gi"
      media:
        enabled: true
        existingClaim: nfs-media-shared-videos-pvc
        accessMode: ReadWriteMany
        retain: true
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 500Mi