# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Tb9AuqoOl3yiIA==,iv:5ggAn+oxsLX+0J7XFGieesEMGM0CKnejrngn0a7SKJo=,tag:PLncWiUd3HTZl+eO+8NmNg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fQhEE6q90R2xmGe61M88i/ZS,iv:hhJ4UskSuSIIevvVPZc87aXu6nFtINv64MhAS+g5eMQ=,tag:UwExWLI2S+Py5Dx2lgjFDw==,type:str]
    SECRET_DEFAULT_EMAIL: ENC[AES256_GCM,data:0wvjg//5mwMQYPnN0vPUxVvQ,iv:J+6c865/3GPWlzK4lVZ8XBEpt6moFNCSYMg4xDV6QZw=,tag:Rx+VI+lGzIqFFpPU49Fbmw==,type:str]
    SECRET_DEFAULT_USERNAME: ENC[AES256_GCM,data:Q0t5FMVpxw==,iv:Fe79qR/OMZBH8N77usJxr1dG11PE3BE+veS49KsYQQ0=,tag:2lYpyh6QO1k7yyfdWrEAgg==,type:str]
    SECRET_DEFAULT_PASSWORD: ENC[AES256_GCM,data:1F6XLeWTwKd0,iv:enX5af/6dukZYU0eiKEQ5fGaXB1oGEPr56SYErDJCto=,tag:PSc/wwqGJ/onofCODoPmFg==,type:str]
    SECRET_SMTP_SERVER: ENC[AES256_GCM,data:WQOAcMH344JtTrFeejd3uWkd5TwIxCSmsByRvk2RzaUrxiB+JZfC,iv:qxhlJVmWED1eTdzi0gsyh8MxIBrguw0DigtJYhhXcZc=,tag:xNACTjSl3VZZQnmuhHenpg==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:kDqv,iv:ubMTl7YaH3kFjuW1UlAI5USpSdgifBAlA8JligQe6dY=,tag:dROGN0plpXxJvrNjfBf/Rg==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:I2hlsBElJwOWQOziOaByDc3He2U=,iv:BzSuN2vgUeksNChaIvEcNlZc9AySG4L5o643BaMnicQ=,tag:okzpM4J/LxTg/6e5VG8TGA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:rZ8c3WabXHlrQB2eeTHPi/ROt7HXGR6pRgzYSdkkvgRGey9CB9yBsiVnZpc=,iv:GAfDjB23zkagWk+VjZo/t/lUVvHZcgeH43rrulWtMCE=,tag:wZsHy6k4QTiBNcxOmX0VHg==,type:str]
    SECRET_AUTH_SMTP_SENDER: ENC[AES256_GCM,data:VNSEMOpk7LMyPa8EsfGdx6FZ6p/gUD3sxovWNmFC,iv:TmOQeIA7PQZ6AEX86qwFYPjI6zHVyp5yl5z4PgbQZew=,tag:w1UnKRR9wTEzvjH3DdGTAQ==,type:str]
    SECRET_WEBHOOK_TOKEN: ENC[AES256_GCM,data:ittcKGHYP9Pqw31jfsWhuXI8iCM5qKj3TLxU4jkVNHqYrjKRSmbAnw==,iv:3eJY4VInhltx06SjItvGwb1RwG15tes/dg+h7DBErVY=,tag:l0DN7U/kbEBkpHjLor+P0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc2ZzMGxtUzQvWjl5Visy
            NjlHRCtaN2hPZzMydDFKL3JWMktxY1F5dVJVCks2VWZUampzdDBCN0dDbDM5b0tW
            dWFTWVZZYUxqQ0hxNlh3ZTBJTzFzYVUKLS0tIE01dmF3M0RHT2hjbzFWclViL3Mw
            eXgyYTBaUnhTL0ZFZTVFYy8vaHJNWnMK1FaY1oNonyOu5cpAxNJAZK6FqBE9mVzs
            +4yXnRq0Dr3wdQXFKUJ0rRka+kItvS1/txMuj9LaHdqfVfqLvEVDWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-21T00:23:21Z"
    mac: ENC[AES256_GCM,data:GInLNxBJG1ThZ91hpdKeuLPj5CuyqirQ1KMqSyo7fku+p1zMtkuCi31FC4+0IermhZ1Tu8K6+asRx1EcH4g3dXrw9nj+5+A7ZrBPQVy+S3M1lAac6UrX1pM5GtLQsXj5mr3r3u0dBG2q7u4l/RCVVOdG/gEtn+RMW/PO0mX1fOk=,iv:nbMqVTKj4qkxqkrvF7Gxjkn+cc+3T8E0yPugjorTTA0=,tag:DJdUGIrYBzxMpDbs1imCSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
