# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:us89N3ac/aLT2A==,iv:i6LXyiwopGUs8dI73by5i3O7qdbWBq/r2iITu5EEUTU=,tag:MsBwvt719NK9S/CKGXGrCQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gX8iOucPC7XdY/y+Fm9E28BK,iv:4PBa1Re7lP21eeh7lUWjqKkgUFcx8SgcwXQvjBX7hjU=,tag:JT9SXlaxzUHNLPdH0j6y5g==,type:str]
    SECRET_DEFAULT_EMAIL: ENC[AES256_GCM,data:thuMozHKWazheYToGDS9fx/r,iv:6z6eNp9lOZj42m0bWccOwIvRuI8EYmfC2/oPhbdve9U=,tag:lMhAgEkU/0cYrM+rKdo1qA==,type:str]
    SECRET_DEFAULT_USERNAME: ENC[AES256_GCM,data:1msbDmkmDA==,iv:7ZG5Xj+zv3n3i6r7OaqPVeNt3/W1nwUwS1j13rM2Lj0=,tag:RjXJgb3JiVYUmQktMgBHsw==,type:str]
    SECRET_DEFAULT_PASSWORD: ENC[AES256_GCM,data:6xdUCKuSKMgF,iv:R0tdbsgXibZsFdFbF9E+OKIuLkmCDn4hzbHgiPhCRPY=,tag:WzWhYv9xacXNZDHsHV/DCA==,type:str]
    SECRET_SMTP_SERVER: ENC[AES256_GCM,data:bE5nJAjqoJcV5yXHtsTzfM24BvYSko/bYfbTCtt2VOEc4e4lthea,iv:kXJ/DbJ6RowVvTV0E+4ixuutTkBaB5m1fFTnbOqYfpI=,tag:OBTfXHotUXWoNvQvN3JHnw==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:UtSX,iv:3jKLFTAWESWm15Y88O6l+2DoUPu0aXmUYmx3WyNmfeY=,tag:gTQbq3gJED4pIHp84KMwgQ==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:u/FSpXTIaX2iUBFbSGwQQ1KCDXM=,iv:D+z0lRqeg5NUVEm7egn0N1nm4zwqX/7Cnbyf6btct8g=,tag:awgQQgqj6v4N1YDEeWmTPg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:sy6KNHcp+HtExBqN6L68deQM3NLe4ybHW6vwpUvfCABuEOyAk+kth/t6cYU=,iv:4lGpqR7RqSa5COrfhLIZjxtYMQw4aXA10D+F/DjrQA4=,tag:0qMnDON0hm03pLcmMa0www==,type:str]
    SECRET_AUTH_SMTP_SENDER: ENC[AES256_GCM,data:uNqI0OBlGLPifzkEvA5oHnI71w==,iv:Ak81lD15FnsB+fW0LD8XHEbAgLbYOUmb0W41+Tt0JxE=,tag:bAlyJfIYv/vgz1WV7ZqCnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UFFjSS9qYzU3Y05ZYXNJ
            Z1R5Y0pxZFFkZENxVklQYkU5TmY1OUlhQkdrCkd3TnNWY3ZrcCtYVk5QWGZnSWVE
            RDQ5ZDNOVEM2Q010TUpkMFpyZkQ4YXMKLS0tIFNiZWp3THB0Z2I2UnhIRWJZV2JE
            NmhzQ0NSTjNRaUNaYTdoUjFrZ2dSZGcKLXHrW79R+jo1uiwOa0PqV8e6wHfgM3X8
            uPVWfL4JlygP/SevczaxL0WCXBtLfSSL6SyFGkzqnOTE/5ekMrLmPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:14:41Z"
    mac: ENC[AES256_GCM,data:pBAKRw7M3zi/3GRizUUwp4tIIr5gsiVAZPwczr1+p+mwZ26YE0UAUpI7DpXF3aJMd4NHZhgSHN36h05cKDLMJYXu9azk3pthC3ve4PJBieKrXnRxv4yEPyYcc3wXqlKLqHs5GErkVTG+H32QAgZGmVy2y2BNBJYYge9dAAsVoqM=,iv:ZE4/VzEiIFi8m0SbmFV0vM7sUTSJT9ENZp04I/dGPfE=,tag:KqHPUDMEZdVSkGdHIlWhiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
