# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:JFFL6Zd9kQZMkg==,iv:tT6lpFURSVeuuCQkUEuHYBYLhR2GFBzhC/2ebtQoV6k=,tag:/PBmGwBt1eyHK14A0ZnQOQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:4nRoHQd/+Kj+gXmY9OnwvUpt,iv:vbLf9ao9Ocb2E012JnDWDzFmeZuq0r+4eV4S8itlMwQ=,tag:5AT5KmSUWXC31NGjew5hLw==,type:str]
    SECRET_DEFAULT_EMAIL: ENC[AES256_GCM,data:jY9fWaRNNfELqCH8AP/V4ji+,iv:1WBmVd7WyFeHKxl0esE3RNJAyBu3hoO8m7FjBWA6DXY=,tag:vg01HZhSC8W/eoZ547fXUA==,type:str]
    SECRET_DEFAULT_USERNAME: ENC[AES256_GCM,data:EnREG0tPEQ==,iv:SL7s/fzk95P1wy2A36G/xx+HvVQnP12stLffL9Yajco=,tag:ZsEfUbQfcp4Kt1y7ALdTsg==,type:str]
    SECRET_DEFAULT_PASSWORD: ENC[AES256_GCM,data:nhkUCEEANRVh,iv:FbcEAD8EE4HuIQLEsxafI1Xfh1lobdk0OuSWm0CPNX0=,tag:LM0pVvsT1wYBseTmXnj4Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NCsxZmJqemhBelJXR1ds
            NVF6ZkFNVE0wMFVBQVNpelMva0tPZms4VmhrClV2QlZpYm1FMjROdWlHYkc0SUx1
            ejZzSmRJN1ZDWW9EcWlMTXFxUldzWkEKLS0tIGIvK1JlaktpcklybG5oY0Y2SFNr
            RE5ydU53Q1V5bXptMFFXZHVYZTVQNHMK50vXH96If9uuAm1G4Tas6hvfccMbbJjH
            ZiGK8xOKkGXvJrue4zXf8ZZzVA/+OhQVjgY6Qx7uAEU8E+Sakcv8UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T05:04:29Z"
    mac: ENC[AES256_GCM,data:vldGlEsWDcjLSRkr/UJsDKj2XG3XleNYHg/7be9d9EBukyWiE7wfnlQUWEpO6E4/dbMTWcOyt5lIKVfTNfTalwX5DwFzDPF/ON5x8UBkZSbRhWF3I6mn3U+5qTq+tXNV5Z4Ws/rRWxk9P6auhfYzvcq++9oC2zsOaNJfVQHDBVM=,iv:q+wxBxyWgxy41JprpIQ2tpTkXAkrioUtybXuxM2wf3o=,tag:ieLU/bwoH8IZja3RjAZZ9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
