---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LDAP_BASE_DN: dc=lethek,dc=net
  METALLB_LB_RANGE: 10.0.3.1-10.0.3.254
  LB_NGINX_ADDR: 10.0.3.1
  LB_TRAEFIK_ADDR: 10.0.3.2
  LB_LDAP_ADDR: 10.0.3.3
  SVC_NAS_ADDR: 10.0.0.100
  SVC_PLEX_ADDR: 10.0.0.1
  SVC_UNIFI_ADDR: 10.0.0.200
