---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: example-secret
  data:
  - secretKey: home--manictime-init-admin--password
    remoteRef:
      key: home--manictime-init-admin--password
