apiVersion: v1
kind: Secret
metadata:
    name: external-secrets-azurekv-secret
    namespace: security
stringData:
    clientId: ENC[AES256_GCM,data:EjLIRdAcJAtX/5mKQNRV9fcIjrvh8nVEx23hWRYPYo9DWSN/,iv:UqDRRLnFZftNy2b4HnJx7LlBPacFNuwwuDx0W/E6YRQ=,tag:akqpzCaW3PL689P+lpKcag==,type:str]
    clientSecret: ENC[AES256_GCM,data:24cijvjTXsnltT7H6YzpxRw4nD7SiG38dr7+80eQQ0SlA561dBjNlw==,iv:c+KwJPAwvNhYXOq0WM/gxXu0A1GpICdNIVntAnFag18=,tag:AMmumwLnoEMcogAoyj3omA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWUZuWUx6S3IyekZWbW0v
            aytiOXNIdW9pdHJwMW1jb0pFWjArUnNONFEwCm5VejVvV1RXL3lIN2lyeVJlOU8v
            TTk1c0FDeGFnT2xSenA2a0NKSDFrRk0KLS0tIEtEM3VyTkMxWjJLeitwcGZrY1JY
            OXBDSzkxdFM0STRSeVdQQlZKbUc2QW8KFUN4HBBbnlodZfZYN3mLw5jYpMw49aRm
            4zrMsYa7DuKikWw0UWtu+LSpA12DRbtIatEXuSQp4yc1h+4SP23AQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T02:12:29Z"
    mac: ENC[AES256_GCM,data:+oPZFsW76mMNvbUolysDGP3kSEHQFoytdEUE42pMlKfmC/GrNGqisBvzuk/adzumgonpSKFYBxbsl+99au3YPTjsY9HtrDHOkXisf5Efx8hy7+KUA5daWxJ4Dv10yt8Jhx62TC6RRM8wx9CxLxPcfl3Ed+utwt6nKCtd6OeeIro=,iv:Qv73RySnKJjhFTw/43o7hGeN6GAk29sK/9XkyXCFgrw=,tag:zTX7qMHU8HCVEyZ+Vt71mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
