---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: networking
subsets:
  - addresses:
      - ip: ${EXTERNAL_UNIFI_ADDR}
    ports:
      - name: https
        port: 443
        protocol: TCP
