---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 13.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
    controller:
      enabled: true
      replicas: 1
      strategy: Recreate
    settings:
      automaticPortSetup: true
    env:
      QBT_BitTorrent__Session__DefaultSavePath: "/downloads/complete/"
      QBT_BitTorrent__Session__MaxActiveDownloads: "10"
      QBT_BitTorrent__Session__MaxActiveTorrents: "20"
      QBT_BitTorrent__Session__MaxActiveUploads: "10"
      QBT_BitTorrent__Session__QueueingSystemEnabled: "true"
      QBT_BitTorrent__Session__TempPath: "/downloads/incomplete/"
      QBT_BitTorrent__Session__TempPathEnabled: "true"
      QBT_Preferences__Downloads__SavePath: "/downloads/complete/"
      QBT_Preferences__Downloads__TempPath: "/downloads/incomplete/"
      QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: "false"
      QBT_Preferences__WebUI__Username: "${SECRET_DEFAULT_USERNAME}"
      TZ: "${DEFAULT_TIMEZONE}"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    service:
      bittorrent:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LB_BITTORRENT_ADDR}"
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            port: 6881
            protocol: TCP
            targetPort: 6881
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        retain: true
        size: "1Gi"
      downloads:
        enabled: true
        type: pvc
        subPath: bittorrent
        existingClaim: nfs-shared-downloads-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
        hosts:
          - host: &host "torrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - *host
