---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  dependsOn:
    - name: external-snapshotter-crds
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: external-snapshotter-source
    namespace: flux-system
  path: ./deploy/kubernetes/snapshot-controller
  interval: 1h0m0s
  prune: true
