---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  path: ./client/config/crd
  sourceRef:
    kind: GitRepository
    name: external-snapshotter-source
