apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:44esnUhZwlOVYX0CPPLbN4Peh2DRfwRomqIWuxaltkwBegeKF8Hzwy1FnaXC4vZc7b8HAkiMiy4SW70a,iv:o3Y2L5tH653i5vkzizMenckN7BQI7oSWoueh29xzIzI=,tag:N4lpUqNy0Sf4r9UsGiRxhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZGNabjFING1QeUlLdlc5
            RTUvY1pnWFpnNkhoYjU1TEpsU2JxU3UrMVc4CmtYcWdYRzU1blpQdHo5YXBkRit6
            cWU2U0lVbml1dzU3QjNQUjhMRnJIOGsKLS0tICt4cmJmbVpHdTk1OHN2ZzFrcFhV
            bHM5THlpTGlORjdWMzladFl2dzNXODAKX99fw55mSYGUCqlUoH/174FMNbg1V2RM
            pabsFI7qjxsd1isfArmihBpTmsKXE8auP5M4lEQGK/acjjRZ4Jz/yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T10:31:11Z"
    mac: ENC[AES256_GCM,data:Wl3BrJXgZvpLQ3nGIMiVOrXjpKHa9aW4G22FVwcz9KnKTevpTGDukTJ5Ptw7uPTq2jZNt3jB8TP6E0C9g9cyqVr+ZkMWiRbiYtzNA7bU62ZxHf86a5PvH0X/92oykw2gRXcpCQ72MF0vrWMxkiYXPIIdjmxf+cOLWuN8FNpAV+U=,iv:gyqI/FeEBeBC0HRDdjWE9WYEQTjUpg50mdhGymfV/xM=,tag:etp2a8nKHdjCY07/MKgkHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
