apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:wqqu3Fp2GROLHbnmQiT5R4J43Jz72MznWhPzG54c14yib0/IEbaFOZI0HMBvPvszeceYOEyBXzpk/xBW,iv:Cdyhjshl/7IN9JlTos/cAEXedtaPejoPIxaqxx+AHkA=,tag:t1rtJasU5JQw8EdGm/MCww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQnI0bnpQQk9UU3Znejlv
            N2ducTc1WThrZmpxR3U3VTlBeGJkS3lablRNCnMwTVJGMWhrRHpWdjNSQWlKTjg4
            YnRqU1Q5VDk2UzFlMGI2UkhYSlBGcEEKLS0tIGtBTkZFaGo2VkNuRGE2WHJIYnp3
            Wm51OG0xUXFrcXhaVUdWdGxiSE9mdWMKhNItLJ6nUXHRBhyO8T78pAv5SJDHmlmn
            Uq2ekKCLRjw3FGz6bV4/Rd1bmo0yrypQOKsMDc7/PW6+7SmwoyHhvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T05:56:07Z"
    mac: ENC[AES256_GCM,data:4eOlmm4VO4gIJKIMHj2hXgQL/4wVvlTXS/DVOAGD7/tKpebQ1Rq3Xa4833FonWJPFQLKbXz14L7speD5xqbpTcpEr/EQuMAPnrPGOB3H2wTX5COxWmqLBNb2h+Pt7gPZhEK91X1fRbzroVYwKXtHmm5lPPx6TxXStQesdmOYYcE=,iv:R1Lk6S3dLJhnu/Ka+2tW5SUn+2gUZc9QVNuxp0Jm9nE=,tag:JPAl3EwS5zIB2bvY7OQdBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
