---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.goharbor.io/
      chart: harbor
      version: v1.8.1
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
  values:
    externalURL: https://harbor.${SECRET_DOMAIN}
    notary:
      enabled: false
    expose:
      type: ingress
      ingress:
        ingressClassName: nginx
        annotations:
          kubernetes.io/tls-acme: "true"
        hosts:
          core: harbor.${SECRET_DOMAIN}
      tls:
        enabled: true
        certSource: secret
        secret: 
          secretName: harbor-tls
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: longhorn
          accessMode: ReadWriteMany
          size: 20Gi
        chartmuseum:
          storageClass: longhorn
          accessMode: ReadWriteMany
        jobservice:
          storageClass: longhorn
          accessMode: ReadWriteMany
        database:
          storageClass: longhorn
          accessMode: ReadWriteMany
        redis:
          storageClass: longhorn
          accessMode: ReadWriteMany
        trivy:
          storageClass: longhorn
          accessMode: ReadWriteMany
