---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  METALLB_NGINX_ADDR: ${BOOTSTRAP_METALLB_NGINX_ADDR}
  METALLB_TRAEFIK_ADDR: ${BOOTSTRAP_METALLB_TRAEFIK_ADDR}
  SVC_NAS_ADDR: ${SVC_NAS_ADDR}
  SVC_PLEX_ADDR: ${SVC_PLEX_ADDR}
  SVC_UNIFI_ADDR: ${SVC_UNIFI_ADDR}
