---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  LB_NGINX_ADDR: ${LB_NGINX_ADDR}
  LB_TRAEFIK_ADDR: ${LB_TRAEFIK_ADDR}
  LB_LDAP_ADDR: ${LB_LDAP_ADDR}
  SVC_NAS_ADDR: ${SVC_NAS_ADDR}
  SVC_PLEX_ADDR: ${SVC_PLEX_ADDR}
  SVC_UNIFI_ADDR: ${SVC_UNIFI_ADDR}
