---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Brisbane"
  METALLB_LB_RANGE: "10.0.3.1-10.0.3.254"
  METALLB_K8S_GATEWAY_ADDR: "10.0.3.254"
  METALLB_INGRESS_ADDR: "10.0.3.1"
  KUBE_VIP_ADDR: "10.0.0.20"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  EXTERNAL_NAS_ADDR: "10.0.0.100"
