apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+tvv4PbhnEAeOQ==,iv:Wg72JbmXZqe/T8ZVZGNmRCxS9JGmn6hZfhi0VpwZAng=,tag:C2nbOWsBWUjnndISzmhzLA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KxxATkOZGGc+PEup0KckVwdm,iv:mP4Fg2imjoKebfXf4cBF031IPF8ELOL10u9UZyScVy4=,tag:5y2wXaMaPf6kREv5LHjSYQ==,type:str]
    SECRET_AZUREKV_VAULTURL: ENC[AES256_GCM,data:Zn0/7UT6BjVYYrZLFCKd5Rl6Vn/Xq0pq8bngzUKT1CxOBQ==,iv:OG13kKPkjt/7dhHUZD0O5l5z6isVVGtdAP2JIClJ8MA=,tag:+M47shRhCCKTtU03noTVAQ==,type:str]
    SECRET_AZUREKV_TENANTID: ENC[AES256_GCM,data:ohvuCXYxLPyWSAHiYBWWlTHfztwgVID1/oW58ZHeRy3GOJXf,iv:GfyNbRFW5UhzwoH0+kdTKA4leFi3l/ZkIvKTdRpceM8=,tag:pd1wURqVSACZVVrFyHVP7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdzhyMHIvc1B2TldaN1Vi
            bXdNcnhvV2NCWlZ2alNCQmNOeGs4SHBLUFhnCnhqcDhPTEpYNjk2bjJrNm5BdWZB
            Mys1Wmk3MXNXTk5henhMWVNnUkg0cFUKLS0tIHZWZ2NOd0l3M1I2NDBCeVZIRkxJ
            djBKYXVDbFZOTVVxU2RPbHVyRDluaTQKsw7BtCxU0727v763+n3beakCcBbiJsnK
            ObSyhV4J7vH/zho+inC6jBcmOU+jnpewD36x1fn9qEFzbFfPdETBXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T07:34:40Z"
    mac: ENC[AES256_GCM,data:iUGrZOamJ5c3b5uutifPSHk3OURxmZwoKtW1LSATktQlZndQuos1FEJI49UwyT6YlRHZOpErKU+37Egyaiu1mLH242K59lRHLhhLtbkicCmsylFV0JQ0leJ4Wseg7Au4UcQKbGuSOoH3qosuPnSBqY+97oFkTqcBgzGC+bqCkxE=,iv:XQNIQD6/v7xKiTGILlz1uGpdZiJ8h5MCdrBrduoToGg=,tag:wHYTEoAPnPfsJwQhrztFIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
