apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8uu4CNoxwnNe6w==,iv:pB3XDs81ojhj4GNjIgGJaU12c4Tm4k52tCpjZBtkbMs=,tag:5dZVcMoOdbmM0MVHQd/Lqg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:riZZ1lVpXMFK5THv8q9yqpqo,iv:yq2X5/oJy0w6kzkk9OxktiVgHLB1/UxJIfZVw65sKRY=,tag:Et5sishNGiqJ9TuoHe32Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ1BNNTBrT1h5ekFJQUJQ
            cElpS2U4ZUZMc2YxakpFbklDb0VrODg1cFdnCjJxS0J0cFJHeEFlZUJCdnM5TWFy
            czFzN0RyUHRQYnZTRDZqTGRzRUh6YmMKLS0tIHRhbkpDdVRkS3ZiNFdvdEVnQ3Fq
            OUJ5RWp2N0tRbitjUDZPVHpXYjhZbVUKcSv/ZGOQOPZTGJLSSRc/pCS5HRAN1u4S
            uNI+aMAvxd1sK8F2Q6PEaQa/DmTXalSvMgM/3gVrtolugf+cAQVVcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T13:10:00Z"
    mac: ENC[AES256_GCM,data:CXYrfIPu7Y9iZ9mSZJu9dtk49NbLHpWbX+THC4Sp0ij+ch7TcAKHtPl3kLa92uyJiT3KPqntcqA6i4hNX5Y6Pp9DeLr1PKnTJvY6aXCX2fmmzTKS9OgLmG+13T42FF8pxFh4ePQwsf85Sv1Ce34niJGC8PEx2DXnrYYQ3AxoTM0=,iv:/iq7iK6DWLg9DOzSsqDNnkBFLTnZXHpZOlUfcevRe5Y=,tag:19j/Q0O961noxGZxJqB9BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
