---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: v9.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/sabnzbd
      tag: latest
    env:
      TZ: "Australia/Brisbane"

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "download-box"
        hosts:
        - host: sabnzbd.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: sabnzbd-tls
          hosts:
          - sabnzbd.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: "100Mi"
      downloads:
        enabled: true
        existingClaim: nfs-media-shared-videos-pvc
        accessMode: ReadWriteMany
        subPath: Downloads
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 500Mi
