---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-user-manager
  namespace: networking
  labels:
    app.kubernetes.io/name: ldap-user-manager
spec:
  selector:
    matchLabels:
      app: ldap-user-manager
  template:
    metadata:
      labels:
        app: ldap-user-manager
      annotations:
        secret.reloader.stakater.com/reload: "ldap-user-manager-env"
    spec:
      containers:
        - name: ldap-user-manager
          image: wheelybird/ldap-user-manager:v1.8
          envFrom:
            - secretRef:
                name: ldap-user-manager-env
          env:
            - name: SERVER_HOSTNAME
              value: "users.${SECRET_DOMAIN}"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
