---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-user-manager-env
  namespace: networking
type: Opaque
stringData:
  SERVER_HOSTNAME: "users.${SECRET_DOMAIN}"
  LDAP_URI: "ldap://openldap-openldap-stack-ha.networking.svc.cluster.local:389"
  LDAP_BASE_DN: "${LDAP_BASE_DN}"
  LDAP_ADMIN_BIND_DN: "cn=admin,${LDAP_BASE_DN}"
  LDAP_ADMIN_BIND_PWD: "${SECRET_DEFAULT_PASSWORD}"
  LDAP_ADMINS_GROUP: "Admins"
  LDAP_USER_OU: "People"
  LDAP_GROUP_OU: "Groups"
  LDAP_ACCOUNT_ATTRIBUTE: "uid"
  LDAP_GROUP_MEMBERSHIP_ATTRIBUTE: "member"
  DEFAULT_USER_GROUP: "users"
  EMAIL_DOMAIN: "${SECRET_DOMAIN}"
  USERNAME_FORMAT: "{first_name}"
  SMTP_HOSTNAME: "${SECRET_SMTP_SERVER}"
  SMTP_HOST_PORT: "${SECRET_SMTP_PORT}"
  SMTP_USERNAME: "${SECRET_SMTP_USERNAME}"
  SMTP_PASSWORD: "${SECRET_SMTP_PASSWORD}"
  SMTP_USE_TLS: "true"
  ACCOUNT_REQUESTS_EMAIL: "${SECRET_DEFAULT_EMAIL}"
  ACCOUNT_REQUESTS_ENABLED: "false"
