apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k10-system-reports-policy.yaml
  - k10-disaster-recovery-policy.yaml
  - default.yaml
  - dev.yaml
  - home.yaml
  - media.yaml
