---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: media
  namespace: kasten-io
spec:
  comment: ""
  frequency: "@weekly"
  paused: false
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources: []
          excludeResources:
            - name: nfs-shared-downloads-pvc
              resource: persistentvolumeclaims
            - name: nfs-shared-media-pvc
              resource: persistentvolumeclaims
    - action: export
      exportParameters:
        frequency: "@weekly"
        migrationToken:
          name: ""
          namespace: ""
        profile:
          name: media
          namespace: kasten-io
        receiveString: ""
        exportData:
          enabled: true
          overrides:
            - storageClassName: longhorn
              enabled: true
              exporterStorageClassName: longhorn
      retention: {}
  retention:
    weekly: 4
    monthly: 3
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - media
