---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
<<<<<<< HEAD:cluster/apps/kube-system/reloader/helm-release.yaml
      chart: reloader
      version: v0.0.124
=======
      chart: metallb
      version: 0.13.7
>>>>>>> remotes/template/main:kubernetes/apps/networking/metallb/app/helmrelease.yaml
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    psp:
      create: false
