---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    controller:
      kind: "DaemonSet"
      ingressClassResource:
        default: true
      publishService:
        enabled: true
      service:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: "${LB_NGINX_ADDR}"
      daemonset:
        hostPorts:
          http: 80
          https: 443
      config:
        use-forwarded-headers: "true"
        proxy-buffers-number: "8"
        proxy-buffer-size: "16k"
        use-http2: "true"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          namespace: kube-system
          namespaceSelector:
            any: true
    defaultBackend:
      replicaCount: 3
    podSecurityPolicy:
      enabled: true
