---
collections:
  - name: community.general
    version: 7.0.1
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.10.3
  - name: kubernetes.core
    version: 2.4.0
roles:
  - name: githubixx.cilium_cli
    version: 2.7.0+0.15.8
  - name: xanmanning.k3s
    version: v3.4.1
