apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zLL+Zzo0hGAInKUXQAS02ATSTi3h4sccHhEWFhH050wejYvR,iv:baaUC9oNfV3SusvZrDglUJZbzITi9BAXvFC4oKUbBIQ=,tag:jO9D3cOwdafX5Jz9FPtzeg==,type:str]
    credentials.json: ENC[AES256_GCM,data:6jbnAa3SR54yj4x5zxQgeQAJ9BUMaKmQnpb6fX8nOgdcAkc6rXEY1gtYzQmr0Q/7HVcnilzVPtlNNC4FEcqO+9hiA0nZ3pYGaV6jY6+UezBCOpyiDsSSojT0CVugO2howi04D8nzqsEOduaaR2VQ/wUJ68zzwraMjaEdDdxNqHh3CkX2WnlamOscwnU7CeEMMs8N61/3poV4HdEv/etvQ+m1bZhpabAcYHbIDmrmwg==,iv:DJfCIyEdKrPu1ty1Fqnw4vn+yU1JkbfzwFsHACXX588=,tag:/wF7d7cAd435UN1drUalhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U0l5MTNYa3NPaHVFZDVq
            RVRmVC9JSlRiUjFsV0w3dHlQekJuVjhBaFdNCmhPWVJjT3pCeTd4b01rbEMyUFpj
            TFBFZlFFMHkycWFOS2t6ajRMbm9yUFkKLS0tIHJ3RGU5Y0RiYnllZ29SaVVrc3Vq
            TDEvdTBsVzAvVkdLSG1FQlZOaVJheFUKNqpPUcQVci82FuZwhmGMYfAMGnVx7O7f
            KzdQaRBkjErggNuwX1XRrZTdAex6oep2kqLuKTB+PF4Dvgi5H+nslw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T05:54:41Z"
    mac: ENC[AES256_GCM,data:aQrEbqhhe0vG5oCNo4fND0xrj7KT0isT4vYa2dsIt1p2lQx4AplmNuBQb/XrEstsEL57i2+YOydesQgJjRa5qpiLueuObeqrhWuc6C830AsmhnfWthSd6PCfo4M9k5ScZg1vtnZpFxL8kU+nwAz5HFpUuxKgNiFlGvfo1mox/5M=,iv:uc2USrCRK5ImK71OjzzCQwE7tKB9RzmtAxYmCwwc2JE=,tag:cGL08rb6z1O2f3TE/VRGSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
