---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shorthorn
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  fromBackup: ''
  fsType: ext4
  numberOfReplicas: '2'
  staleReplicaTimeout: '30'
