---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  SECRET_AZUREKV_VAULTURL: "${BOOTSTRAP_AZUREKV_VAULTURL}"
  SECRET_AZUREKV_TENANTID: "${BOOTSTRAP_AZUREKV_TENANTID}"
