apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _pvc/nfs-shared-downloads-pvc.yaml
  - _pvc/nfs-shared-media-pvc.yaml
  - overseerr
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - sabnzbd
  - sonarr
