---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emy-data
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
