# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:vn/xzwNBAR9u2rc+HwWXhUSvYgtyS0KLMv/+ywSMCKXi05Icug==,iv:armIBlOWBrDNw3ldTSk1K+gd7U4S6mHgOzl3M7tDNeY=,tag:mq5rIpDnIoZCuSf0d2Uiyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK1NVcWI1VUM5aTJmdDNN
            L2tlTHBEWWlDbEVIMVoxQzI3a1d4dUltVFFZCmxQQ2hJOHVKVllqYkNldGZkK0Z5
            RlFCcm1rTGJpRGJsZ1c5Y2ZOZ1lkdTgKLS0tIGxXWDZpUnkvSkZseVZJTG1tblJL
            LzBZTkg2QjRKcC9RSWZhbC9BZ3pJT0UK1JCHrW1eQMz4JCkSvf9oksy4uHetJ+Y3
            CSJAMouz25N3uxNkGac2LUZWYA/8KBCsLg0KKdEdDY07+5+OVw15uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T02:02:39Z"
    mac: ENC[AES256_GCM,data:DPMVu5VYqZ+mAxCRpdXXPylH2y1Ge8lySYFgwBMrI62JftLcuJqqkDvvoJRWs0tUEqsgrHHOgUPPTvzwwIuICfmn8k+3fRevig84ItMDRcxZeTwWdD7bqbaY3FOOM8NGVhtV39+A7+MFahfKawmJgdaV4sltr9EMNZ1TuEa1ad8=,iv:s95qZOSx5jJME7H0fhIzklXVcf4AcSlYBuD4Ad4U2Zo=,tag:CGRijR9r2mRQbqp2a2x9dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
