# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Cqr5YIXwW4CxJJPmOkZ7Za6aJrUhFo//9TJ/u3ab9h4suMesug==,iv:F77/HEEsC72QZNiDFasMqnQX2UtBoQE10nAVYyNz10g=,tag:hMaz90HRhDKP7VuCHPNEvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdmRxQWJHLzAreXY3aG8r
            Z1JpRUU5YW5jaFRrUmxwdm9BK1paVnpSbUVRCmlod0Q1cVU3WUJVU3hMaXd4VHdj
            b0JJbEVxSmQ2MGh1TEtvYURnSkFRdm8KLS0tIE53a0dOSjZmbXB2Y09UdWpHVklQ
            UmFoaVJKeGVTVHdXeTZYZ0VjeEFIczQKbPa/foO7WZNv41Ksy4gdU4/Tj1xtXdjV
            H1Tf5+F5VpANe3fLJ95ENpPEPJQ9r/Z/RbBg60To74AeohxlDVu57A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T06:19:11Z"
    mac: ENC[AES256_GCM,data:91GukBHqeos0EOEb89DmrkkLTAjHIaDrXxXAO3XwMY/2V7DDFFV9q4DrURKmp6XVnSY9jI/PjXqD4UqQdOnl0OUsmqrB4l9nMQe6QucRMtPoQt0YI24ymQkn75Cd0RGzxc8HKIrHdUFMMHJCvrSTzeOOvesPAXr3VKL/Ic+g2zw=,iv:9xNilJPiYXLV1z2pJTAsxWmTt4MpM3TMN8UDq9X4tAY=,tag:p3oErG7A7+FFsPB4fSI45w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
