# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:nFoxfyrYDPvQDZcTgeruTccNwzS0uSi5QUKyNXCQ1RgZ8f4njQ==,iv:ne9QbgWZkB/gyiA92eq7tOBp4tE7qqHWl5q+IhaOoH0=,tag:uNUnovJtTW/hukoFI8HmTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSjFCZFJybG81eVdUT3Br
            UUp0alUrcnZqUEhReGZvZ3VUMUM5cXFZaWxFCmdrOFFWOG0vd1VFN3hHOHM2WDJr
            Z2o4ZXdoUkF6RU01ei80bXZpdjdqZUEKLS0tIHJaSmN5K3NqcXZOTTJlcUR5STBi
            L2JudjYvSVJoRFRiaFYxc0FEZk9VN0EKd1KhIYW9jvnenxMsN91V/KttQy2gzzBj
            qQaOxxRkS/LhaFoM6kTCyE6hGi9Qd2rqmtOWZdUGMMOdwCNyhtQXHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-21T23:56:06Z"
    mac: ENC[AES256_GCM,data:5v9d8pAOoGjpdlMijKuqOIC5QBq9wavgJPMGaMMRDsGTLCEgl6u7kfVBMTk1fzC/oPekBdXAmNotNWcOJTE8BYZTbUJkxnH+Urhzx6Zp8TOY2/GIuKnJ0ZRC97VzROkWqSLpQF0kBeHm1ujwvvdpPB1GdTTN8BuMAdbpMmVNGE8=,iv:xsOLVhXQ1oyMQ7bC2p1A3nBkNsGM0D7ke12jtdoEw4I=,tag:HLSLU7fAng5eHXKgVzyEIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
