# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8NV5Vu73bSN1p0pdo3Ndl4L/KbsJwy8mrh4q3liB/0Hxj7bDWw==,iv:QfZsA5BudCnAcCVscqmx/hcAMXp8VNbPXKpNdXAVXZw=,tag:eNuInYQqOuYiOrLIJb1rDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTlRYbFVQVlBNNGNDZU51
            SzUyQ1drZHVUQkpKdzRTWkNMT2ZST1RzaXhFCjNaeWlXOG94T053YmpZNjBCaU9l
            bkxXYTVuN1U5WjY0ZlEzWVdOSXNXVWMKLS0tIGkwTEdzMGl0My95cE02S2k3ay9V
            Mk9NQWw4NmduU29tZjlUMWdVK2VTOXcKLiZ4Hm0PtUL1t57SUiIavmrEhNUKjwiw
            DXjxd7wZUH+ex0bmH8qx270tB57mL4h0NolDde7zMj1pAl+l7xQLkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T05:04:29Z"
    mac: ENC[AES256_GCM,data:31z4Df4DNn4RQvwaZ9xqEayd83YHkmb8viz5x+KysavFaPoygf89+n55SlrBFrUWzqbgAKyraEWJkNnbAI7ZX4BL+5UjRingosJSLN9KhZhz4bheovZk5tzz0GdyHqrO5iehlw7GVg9k2TVo61WDAA+RxorfiGM79+qumLZAFzk=,iv:TccjIqV+IAGHrHf1NwhZWw0g1/AKXvPN4aKA30p222w=,tag:PfxlbMkNAL9QSHFgzEgMwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
