# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Qm8HBLXffZRm0lOoKKcWkMpM8IxCei4iH0Rj+LWVg6tU9wkcGA==,iv:XOJUe3E8oAubyotU1XEYo1zGs3ntAAGq8jNcofg/ZxA=,tag:cHoULvNTbIszSlvRNt2l5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveUg0dFpRQmFPMG5QeFF1
            aHhobHp5a2dzV0I0YXBHREh6YWU1WFJhMDNBCjFZK1d2Q3k0Y255Y3dKdEhFTkxw
            dTcwVVAxVWdIYmM3RXQydU5tcHF1ZncKLS0tIGJZSG1CaWZzM1hNN3ZldnRPOUs0
            YTYrTHRNbDdOYUd5blNyVkFEZTZ4TlEKg4odNoGxUUHWvWs70rpnFUUam89K/5Zs
            tftf8p89OtM9zu7/HmT8LtlMgUbj2+ztZMYkheJiz5tLYFk2uI6kdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-21T00:23:21Z"
    mac: ENC[AES256_GCM,data:la8cztcuUscEeWlGX+NpR/91h2Y2gm0pyqXpCflPeS4whF8EJiC/SbHIwY+Za7IpWIkQ6s7EEAeFRgXkpcAyZySt4LVLxO1dadbsRatBtofyMUl7q5ILzfA0osFNVzxHz6xnBnFF5zGt+qnk/FLsb/SQ/HHOYqj8HCAVOqJ4+44=,iv:dJTlahYShALwpa+NVyMBnVQ/lUJw90FpeCSUrmR0pk4=,tag:8NhGVmnLC8kGOlDwfDF5Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
