# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:fgzq9E+hYvfTAcWB7tx3C3ROzjT+De/XTsdoekYh03/ghrBW5g==,iv:dt1cwP6O5y26cGBgwak95Y5zxTDALoVlSEl6GfF7UDE=,tag:279UwaNTu9g1ikvBZ5GtgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llrklc0a2hzqrlk6y2eu6cfsgarjl8umzql9wmdt8w2qppnudp8q2jtr9w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TG9xdkxBZUplbnNNM29E
            WGJWaFNMTFZKMmhKak5XcnZWM25aVC9rT1hzCmlIL2ZJeHNITEpSMzNzZVdjNVZq
            SVhHV2g3cWRFYU5IUld4OFQrNkRTcDAKLS0tIEFBOXFKb0xXazUvTlF3VzBHOUtP
            M3lCWWNQMm54bGcxR1BMdm1HcUk1RG8KhihtVTlP0yCIF2gPT4Z3NigTuiLZ7tV3
            CuW8KmmvgWs4/cUJcfm/9GLIPxywGl5RUWSSuuYcTYfw+ubdGg+dzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T07:22:58Z"
    mac: ENC[AES256_GCM,data:2GXJ9Hp1ljqHe05L6mnqlv/bPuqWsm0r8cM+Pfkj/XXoreMD6IBKDfux+OlRsJeCeYArhVLndTDC4gY4K+0SRdob8+hjKqhV1l/7kAo1FH1kLMOnNtBg9Wx4GOSp5mjaHl9PWW+GkhlJNiuSDuuxuFd8LKEv3ezMJpufeH/vL6E=,iv:IP3Zr6slgPPzciLqx0ZAoAPH/e84zsGUjS8f+kza5bo=,tag:tHN4Sz4adMB3PEFq9V+hXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
