# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:2suFFmgqcKEnqyZlslXFQZCNUia4CoEnwVPMZO9rntl62QAWhQ==,iv:QB5LPfE4brwJOLXq3Re4spvL71WJvI1SliS10FA2JI8=,tag:iktPO6L0Ochz7ru8utTYvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMnFlOG5TSEhZdDBURVBh
            QjJvVm16R0tLZlJETW5EZFdUaDIzazd0U0ZvCjN3UVJsUHREdkFnVGVYdFVaUkQ4
            SnBmVGViQVJkaGxkWEZuWCtpMThyTlUKLS0tIHJZb2F5NzdZcHl5TWI4RXRBR3pj
            aFFONDczbUQyV3BGMFpDZG9BVk0xdWMKW8A35EZLARwhQ9fGLptb3b7LmESqJc2y
            4eAwW7RAPJMYL9SNWUA4pjGPevwKr5z2t9F5RJnkmLQqw6hjyYXFJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-20T04:21:21Z"
    mac: ENC[AES256_GCM,data:Yg9KHRRenyUv7FnzhKiqkhbupqfbusxF/LldTWBJ0AnRJNIcmJbE+oRVus3FqB3Bg3N98gf8paMAQBS2egZigxLSqoym7JMpi2PRqR6cBSn02ILCRJo7ZCNV4SB5okSw7twRXse1crvTc/H55LwLp6SoeDTb4e1HmMIVfSWF4nc=,iv:T1XqyaNel04JcSIItpWOxg7wHT9wqcv8ebyMNqhWI38=,tag:Yf+oVL9/UwQ1wQWZzsDJOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
