# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:rt/IsdA4VYvvk2W+Lw+yZbuKn1M7yxRcEt3LghjgIJHlpyKrgQ==,iv:p5AZREhc0IFww3dAdsuVzOLmTobxea46+BoWIyrDleE=,tag:kp+HJqSClpeqcRQ7Bk2waA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ1A2WW9mT05keGZBNm8r
            MkQ3R0VqVWtteDIvVldCZWlOMENKK0pzc2dvCmZvNGQvRUFEdUNkdGhlWDdIUkdz
            WWVlOEQ1L2ErTDd6YmxOTlFGNzloOFkKLS0tIC9WaVVuQ2xkeDNBUWFHSGUrY2Nl
            TXVIQlRjZjA0bG42RDA2b0xWVm4wbkkKh+MVD98TQSVS3NiRF4ICJy8PUjxSFTYe
            jJBsRbX4QAOrUgACiXaGk9D/i3u0cm2G+Ig+v4WkMYqMkkthbUiPwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-22T04:39:01Z"
    mac: ENC[AES256_GCM,data:FAZ95biqKZ8IUD8WiMpm5AAImdJR6Mpql5h4THdxHRZLTCtcFPMZ+JZREg9zFTEyuMWYjjL0BzkVohu/KH8azsglSSWJtgaFYbOtENe3Q5YtpZYE4Zj2hJ0QFyx4Mict7mjbSgDk00JtveIjCHKqwWNkbkDCtSEWJEt6aykm3CY=,iv:VlM18TGIly/OvO7OWVkIM2KlWhoMaySAkqIeRKsKcgI=,tag:iKbmO5MdOCzx6L/vYcuqcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
