# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Qd5aoglM8M67YQCv4wRl9TrE+P+fNehYHENI93ptmkENLYcc0w==,iv:n3vgH1MQASmnh6st6S5Xxd54D+fWdOCaUukHoUaO1eE=,tag:dZEE2B/1Y+XQ33+MhZywug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZllrcVcxQi9GZjFoL3RG
            UUt4dVFTVkZ1TlBUenFqZkxOQXBpOXMyVzNvCjhzUjc1bldONnByUVlBNkhZUlM2
            aWI4U3JTQmdBMGd5YWc4K2Uyd2Q3UlkKLS0tIEdWcTE5M2lkS2YxaWllS0toWEJw
            RlFRMzlodVp2R2JhMUFmR1ZoWEZ3Y0UKDkiEUE4OidByNYujKTdOp6LVUAPta3pd
            K41T98A/fo3MxoHtPNzQFwIU/9+DTFyrUYFhGpvrHpNpcyYH5+xcRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-21T01:23:49Z"
    mac: ENC[AES256_GCM,data:reqGhB4ui15r9L0yegFzZKN1hQqLgxqhsEl9ld7F954uau6qP+NoUzo6eqWi1fIzjb4EmWJGq4beGwcALN23evcwqPizr+2WhuFd+PYPdkWbdD+kGU++7fZqyNKcOsp0dv1af4eceikauEGPrAbPovzkNyk4pSDG1+0qcKmcAno=,iv:J0QzayP8rtVkR3w2vOytmNCoiylnZH7J6WELJelFJGo=,tag:aSe0RnKhbHcbzKiK81PQ7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
