---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "${BOOTSTRAP_TIMEZONE}"
  KUBE_VIP_ADDR: "${BOOTSTRAP_KUBE_VIP_ADDR}"
  METALLB_LB_RANGE: "${BOOTSTRAP_METALLB_LB_RANGE}"
  METALLB_K8S_GATEWAY_ADDR: "${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}"
  METALLB_INGRESS_ADDR: "${BOOTSTRAP_METALLB_INGRESS_ADDR}"
  EXTERNAL_UNIFI_ADDR: "${BOOTSTRAP_EXTERNAL_UNIFI_ADDR}"
  EXTERNAL_NAS_ADDR: "${BOOTSTRAP_EXTERNAL_NAS_ADDR}"
  EXTERNAL_PLEX_ADDR: "${BOOTSTRAP_EXTERNAL_PLEX_ADDR}"
