---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 4.5.10
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    eula:
      accept: true
      company: ${SECRET_DOMAIN}
      email: ${SECRET_DEFAULT_EMAIL}
    global:
      persistence:
        storageClass: longhorn
        size: 1Gi
    auth:
      tokenAuth:
        enabled: true
    ingress:
      create: true
      host: k10.${SECRET_DOMAIN}
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: nginx
        hajimari.io/enable: "true"
        hajimari.io/icon: backup-restore
        hajimari.io/appName: "K10"
        hajimari.io/url: "https://k10.${SECRET_DOMAIN}/"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/auth-url: "http://authelia.networking.svc.cluster.local/api/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
      hosts:
        - k10.${SECRET_DOMAIN}
      tls:
        enabled: true
        secretName: k10-tls
