apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:O9sFP1G9OZxz10vmwCRJ9aV0,iv:uEz4iYTsgtjmnozfmOB4r42wxEZBl4gr5OBjxkHz3ns=,tag:wrfZmh5c1MrjYi/DYItMHQ==,type:str]
    api-key: ENC[AES256_GCM,data:dSdfP3KTv5CwL641EvT7/HfDOJRQcl7Z2+yxp9sJ/jDCcmEBhw==,iv:xB1YMEpW+K4Lfr0oGAggKuBnDbg51iulnxr/vo+pJKw=,tag:GlM0Kbwmm6RQ+C0fkHnz6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dcvfnffwc7uzafweqsp80xhwm690j3dqnhaa00fs4vk3vpqytfrsr2r479
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z1RORzAvY1A3V3JhRGpE
            NkpPaDdEeUJWOW45UEdqSVgxNjNvSU5SeWtBCnVhcG40WXBkRFJiNFFkdVQwN1BQ
            ODVzNjBqazN5Zy8zL2Q1alBDK3kyc1EKLS0tIEJ0TkdwL3ZvemloaUsybzRkamY2
            Vml1Wjg2WUFXOVpiV29VSS90NkFYRmsK2kz8U9k8LuLOfRx58J5QoTDBHW4gdLNe
            x91EFQnvuFTqWto9Eahkv7YNC9OBlwpr6DNrWWHV3b1iZxQnVLMV4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T13:10:00Z"
    mac: ENC[AES256_GCM,data:gmRR9Q3EVvdnztv75cnCSUUb1pT3snq7eQZYHftqDxbVsAx5zn8kuA9ujqY3VEXNBIar3sOGshQFQZyorbE1oB6U8VnCanb5X+u6wlopdrV0BpFrMNrVbvBqyddKJ4GQVb5t7OlbrVi/VFdz8S3RSVBZ/YKq/nDG8GU6kLU9Ui0=,iv:QjsT16zMHyc8LLqaAdyyF7KXs2VMUzfs60sVlUlGUrs=,tag:Jf3LwY9jd8ob04JTe/ZIzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
