apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dev.yaml
  - cert-manager.yaml
  - home.yaml
  - ingress-nginx.yaml
  - longhorn-system.yaml
  - media.yaml
  - metallb-system.yaml
  - networking.yaml
  - test.yaml
